package com.yskj.push.dao;

import com.yskj.push.domain.BalanceSheet;

public interface BalanceSheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance_sheet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance_sheet
     *
     * @mbggenerated
     */
    int insert(BalanceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance_sheet
     *
     * @mbggenerated
     */
    int insertSelective(BalanceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance_sheet
     *
     * @mbggenerated
     */
    BalanceSheet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance_sheet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BalanceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_balance_sheet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BalanceSheet record);
}