package com.yskj.push.dao;

import com.yskj.push.domain.CashFlow;

public interface CashFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cash_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cash_flow
     *
     * @mbggenerated
     */
    int insert(CashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cash_flow
     *
     * @mbggenerated
     */
    int insertSelective(CashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cash_flow
     *
     * @mbggenerated
     */
    CashFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cash_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cash_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CashFlow record);
}