package com.yskj.push.dao;

import com.yskj.push.domain.DisclosureDate;

public interface DisclosureDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disclosure_date
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disclosure_date
     *
     * @mbggenerated
     */
    int insert(DisclosureDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disclosure_date
     *
     * @mbggenerated
     */
    int insertSelective(DisclosureDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disclosure_date
     *
     * @mbggenerated
     */
    DisclosureDate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disclosure_date
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DisclosureDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_disclosure_date
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DisclosureDate record);
}