package com.yskj.push.dao;

import com.yskj.push.domain.Dividend;

public interface DividendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dividend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dividend
     *
     * @mbggenerated
     */
    int insert(Dividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dividend
     *
     * @mbggenerated
     */
    int insertSelective(Dividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dividend
     *
     * @mbggenerated
     */
    Dividend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dividend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dividend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dividend record);
}