package com.yskj.push.dao;

import com.yskj.push.domain.Express;

public interface ExpressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express
     *
     * @mbggenerated
     */
    int insert(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express
     *
     * @mbggenerated
     */
    int insertSelective(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express
     *
     * @mbggenerated
     */
    Express selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Express record);
}