package com.yskj.push.dao;

import com.yskj.push.domain.FinaAudit;

public interface FinaAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_audit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_audit
     *
     * @mbggenerated
     */
    int insert(FinaAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_audit
     *
     * @mbggenerated
     */
    int insertSelective(FinaAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_audit
     *
     * @mbggenerated
     */
    FinaAudit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FinaAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FinaAudit record);
}