package com.yskj.push.dao;

import com.yskj.push.domain.FinaIndicator;

public interface FinaIndicatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_indicator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_indicator
     *
     * @mbggenerated
     */
    int insert(FinaIndicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_indicator
     *
     * @mbggenerated
     */
    int insertSelective(FinaIndicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_indicator
     *
     * @mbggenerated
     */
    FinaIndicator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_indicator
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FinaIndicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fina_indicator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FinaIndicator record);
}