package com.yskj.push.dao;

import com.yskj.push.domain.Top10FloatHolders;

public interface Top10FloatHoldersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_top10_float_holders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_top10_float_holders
     *
     * @mbggenerated
     */
    int insert(Top10FloatHolders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_top10_float_holders
     *
     * @mbggenerated
     */
    int insertSelective(Top10FloatHolders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_top10_float_holders
     *
     * @mbggenerated
     */
    Top10FloatHolders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_top10_float_holders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Top10FloatHolders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_top10_float_holders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Top10FloatHolders record);
}