/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50727
 Source Host           : localhost:3306
 Source Schema         : stock_info

 Target Server Type    : MySQL
 Target Server Version : 50727
 File Encoding         : 65001

 Date: 25/07/2019 19:22:37
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for t_balance_sheet
-- ----------------------------
DROP TABLE IF EXISTS `t_balance_sheet`;
CREATE TABLE `t_balance_sheet` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS股票代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `f_ann_date` varchar(64) DEFAULT NULL COMMENT '实际公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `report_type` varchar(64) DEFAULT NULL COMMENT '报表类型',
  `comp_type` varchar(64) DEFAULT NULL COMMENT '公司类型',
  `total_share` varchar(64) DEFAULT NULL COMMENT '期末总股本',
  `cap_rese` varchar(64) DEFAULT NULL COMMENT '资本公积金',
  `undistr_porfit` varchar(64) DEFAULT NULL COMMENT '未分配利润',
  `surplus_rese` varchar(64) DEFAULT NULL COMMENT '盈余公积金',
  `special_rese` varchar(64) DEFAULT NULL COMMENT '专项储备',
  `money_cap` varchar(64) DEFAULT NULL COMMENT '货币资金',
  `trad_asset` varchar(64) DEFAULT NULL COMMENT '交易性金融资产',
  `notes_receiv` varchar(64) DEFAULT NULL COMMENT '应收票据',
  `accounts_receiv` varchar(64) DEFAULT NULL COMMENT '应收账款',
  `oth_receiv` varchar(64) DEFAULT NULL COMMENT '其他应收款',
  `prepayment` varchar(64) DEFAULT NULL COMMENT '预付款项',
  `div_receiv` varchar(64) DEFAULT NULL COMMENT '应收股利',
  `int_receiv` varchar(64) DEFAULT NULL COMMENT '应收利息',
  `inventories` varchar(64) DEFAULT NULL COMMENT '存货',
  `amor_exp` varchar(64) DEFAULT NULL COMMENT '长期待摊费用',
  `nca_within_1y` varchar(64) DEFAULT NULL COMMENT '一年内到期的非流动资产',
  `sett_rsrv` varchar(64) DEFAULT NULL COMMENT '结算备付金',
  `loanto_oth_bank_fi` varchar(64) DEFAULT NULL COMMENT '拆出资金',
  `premium_receiv` varchar(64) DEFAULT NULL COMMENT '应收保费',
  `reinsur_receiv` varchar(64) DEFAULT NULL COMMENT '应收分保账款',
  `reinsur_res_receiv` varchar(64) DEFAULT NULL COMMENT '应收分保合同准备金',
  `pur_resale_fa` varchar(64) DEFAULT NULL COMMENT '买入返售金融资产',
  `oth_cur_assets` varchar(64) DEFAULT NULL COMMENT '其他流动资产',
  `total_cur_assets` varchar(64) DEFAULT NULL COMMENT '流动资产合计',
  `fa_avail_for_sale` varchar(64) DEFAULT NULL COMMENT '可供出售金融资产',
  `htm_invest` varchar(64) DEFAULT NULL COMMENT '持有至到期投资',
  `lt_eqt_invest` varchar(64) DEFAULT NULL COMMENT '长期股权投资',
  `invest_real_estate` varchar(64) DEFAULT NULL COMMENT '投资性房地产',
  `time_deposits` varchar(64) DEFAULT NULL COMMENT '定期存款',
  `oth_assets` varchar(64) DEFAULT NULL COMMENT '其他资产',
  `lt_rec` varchar(64) DEFAULT NULL COMMENT '长期应收款',
  `fix_assets` varchar(64) DEFAULT NULL COMMENT '固定资产',
  `cip` varchar(64) DEFAULT NULL COMMENT '在建工程',
  `const_materials` varchar(64) DEFAULT NULL COMMENT '工程物资',
  `fixed_assets_disp` varchar(64) DEFAULT NULL COMMENT '固定资产清理',
  `produc_bio_assets` varchar(64) DEFAULT NULL COMMENT '生产性生物资产',
  `oil_and_gas_assets` varchar(64) DEFAULT NULL COMMENT '油气资产',
  `intan_assets` varchar(64) DEFAULT NULL COMMENT '无形资产',
  `r_and_d` varchar(64) DEFAULT NULL COMMENT '研发支出',
  `goodwill` varchar(64) DEFAULT NULL COMMENT '商誉',
  `lt_amor_exp` varchar(64) DEFAULT NULL COMMENT '长期待摊费用',
  `defer_tax_assets` varchar(64) DEFAULT NULL COMMENT '递延所得税资产',
  `decr_in_disbur` varchar(64) DEFAULT NULL COMMENT '发放贷款及垫款',
  `oth_nca` varchar(64) DEFAULT NULL COMMENT '其他非流动资产',
  `total_nca` varchar(64) DEFAULT NULL COMMENT '非流动资产合计',
  `cash_reser_cb` varchar(64) DEFAULT NULL COMMENT '现金及存放中央银行款项',
  `depos_in_oth_bfi` varchar(64) DEFAULT NULL COMMENT '存放同业和其它金融机构款项',
  `prec_metals` varchar(64) DEFAULT NULL COMMENT '贵金属',
  `deriv_assets` varchar(64) DEFAULT NULL COMMENT '衍生金融资产',
  `rr_reins_une_prem` varchar(64) DEFAULT NULL COMMENT '应收分保未到期责任准备金',
  `rr_reins_outstd_cla` varchar(64) DEFAULT NULL COMMENT '应收分保未决赔款准备金',
  `rr_reins_lins_liab` varchar(64) DEFAULT NULL COMMENT '应收分保寿险责任准备金',
  `rr_reins_lthins_liab` varchar(64) DEFAULT NULL COMMENT '应收分保长期健康险责任准备金',
  `refund_depos` varchar(64) DEFAULT NULL COMMENT '存出保证金',
  `ph_pledge_loans` varchar(64) DEFAULT NULL COMMENT '保户质押贷款',
  `refund_cap_depos` varchar(64) DEFAULT NULL COMMENT '存出资本保证金',
  `indep_acct_assets` varchar(64) DEFAULT NULL COMMENT '独立账户资产',
  `client_depos` varchar(64) DEFAULT NULL COMMENT '其中：客户资金存款',
  `client_prov` varchar(64) DEFAULT NULL COMMENT '其中：客户备付金',
  `transac_seat_fee` varchar(64) DEFAULT NULL COMMENT '其中:交易席位费',
  `invest_as_receiv` varchar(64) DEFAULT NULL COMMENT '应收款项类投资',
  `total_assets` varchar(64) DEFAULT NULL COMMENT '资产总计',
  `lt_borr` varchar(64) DEFAULT NULL COMMENT '长期借款',
  `st_borr` varchar(64) DEFAULT NULL COMMENT '短期借款',
  `cb_borr` varchar(64) DEFAULT NULL COMMENT '向中央银行借款',
  `depos_ib_deposits` varchar(64) DEFAULT NULL COMMENT '吸收存款及同业存放',
  `loan_oth_bank` varchar(64) DEFAULT NULL COMMENT '拆入资金',
  `trading_fl` varchar(64) DEFAULT NULL COMMENT '交易性金融负债',
  `notes_payable` varchar(64) DEFAULT NULL COMMENT '应付票据',
  `acct_payable` varchar(64) DEFAULT NULL COMMENT '应付账款',
  `adv_receipts` varchar(64) DEFAULT NULL COMMENT '预收款项',
  `sold_for_repur_fa` varchar(64) DEFAULT NULL COMMENT '卖出回购金融资产款',
  `comm_payable` varchar(64) DEFAULT NULL COMMENT '应付手续费及佣金',
  `payroll_payable` varchar(64) DEFAULT NULL COMMENT '应付职工薪酬',
  `taxes_payable` varchar(64) DEFAULT NULL COMMENT '应交税费',
  `int_payable` varchar(64) DEFAULT NULL COMMENT '应付利息',
  `div_payable` varchar(64) DEFAULT NULL COMMENT '应付股利',
  `oth_payable` varchar(64) DEFAULT NULL COMMENT '其他应付款',
  `acc_exp` varchar(64) DEFAULT NULL COMMENT '预提费用',
  `deferred_inc` varchar(64) DEFAULT NULL COMMENT '递延收益',
  `st_bonds_payable` varchar(64) DEFAULT NULL COMMENT '应付短期债券',
  `payable_to_reinsurer` varchar(64) DEFAULT NULL COMMENT '应付分保账款',
  `rsrv_insur_cont` varchar(64) DEFAULT NULL COMMENT '保险合同准备金',
  `acting_trading_sec` varchar(64) DEFAULT NULL COMMENT '代理买卖证券款',
  `acting_uw_sec` varchar(64) DEFAULT NULL COMMENT '代理承销证券款',
  `non_cur_liab_due_1y` varchar(64) DEFAULT NULL COMMENT '一年内到期的非流动负债',
  `oth_cur_liab` varchar(64) DEFAULT NULL COMMENT '其他流动负债',
  `total_cur_liab` varchar(64) DEFAULT NULL COMMENT '流动负债合计',
  `bond_payable` varchar(64) DEFAULT NULL COMMENT '应付债券',
  `lt_payable` varchar(64) DEFAULT NULL COMMENT '长期应付款',
  `specific_payables` varchar(64) DEFAULT NULL COMMENT '专项应付款',
  `estimated_liab` varchar(64) DEFAULT NULL COMMENT '预计负债',
  `defer_tax_liab` varchar(64) DEFAULT NULL COMMENT '递延所得税负债',
  `defer_inc_non_cur_liab` varchar(64) DEFAULT NULL COMMENT '递延收益-非流动负债',
  `oth_ncl` varchar(64) DEFAULT NULL COMMENT '其他非流动负债',
  `total_ncl` varchar(64) DEFAULT NULL COMMENT '非流动负债合计',
  `depos_oth_bfi` varchar(64) DEFAULT NULL COMMENT '同业和其它金融机构存放款项',
  `deriv_liab` varchar(64) DEFAULT NULL COMMENT '衍生金融负债',
  `depos` varchar(64) DEFAULT NULL COMMENT '吸收存款',
  `agency_bus_liab` varchar(64) DEFAULT NULL COMMENT '代理业务负债',
  `oth_liab` varchar(64) DEFAULT NULL COMMENT '其他负债',
  `prem_receiv_adva` varchar(64) DEFAULT NULL COMMENT '预收保费',
  `depos_received` varchar(64) DEFAULT NULL COMMENT '存入保证金',
  `ph_invest` varchar(64) DEFAULT NULL COMMENT '保户储金及投资款',
  `reser_une_prem` varchar(64) DEFAULT NULL COMMENT '未到期责任准备金',
  `reser_outstd_claims` varchar(64) DEFAULT NULL COMMENT '未决赔款准备金',
  `reser_lins_liab` varchar(64) DEFAULT NULL COMMENT '寿险责任准备金',
  `reser_lthins_liab` varchar(64) DEFAULT NULL COMMENT '长期健康险责任准备金',
  `indept_acc_liab` varchar(64) DEFAULT NULL COMMENT '独立账户负债',
  `pledge_borr` varchar(64) DEFAULT NULL COMMENT '其中:质押借款',
  `indem_payable` varchar(64) DEFAULT NULL COMMENT '应付赔付款',
  `policy_div_payable` varchar(64) DEFAULT NULL COMMENT '应付保单红利',
  `total_liab` varchar(64) DEFAULT NULL COMMENT '负债合计',
  `treasury_share` varchar(64) DEFAULT NULL COMMENT '减:库存股',
  `ordin_risk_reser` varchar(64) DEFAULT NULL COMMENT '一般风险准备',
  `forex_differ` varchar(64) DEFAULT NULL COMMENT '外币报表折算差额',
  `invest_loss_unconf` varchar(64) DEFAULT NULL COMMENT '未确认的投资损失',
  `minority_int` varchar(64) DEFAULT NULL COMMENT '少数股东权益',
  `total_hldr_eqy_exc_min_int` varchar(64) DEFAULT NULL COMMENT '股东权益合计(不含少数股东权益)',
  `total_hldr_eqy_inc_min_int` varchar(64) DEFAULT NULL COMMENT '股东权益合计(含少数股东权益)',
  `total_liab_hldr_eqy` varchar(64) DEFAULT NULL COMMENT '负债及股东权益总计',
  `lt_payroll_payable` varchar(64) DEFAULT NULL COMMENT '长期应付职工薪酬',
  `oth_comp_income` varchar(64) DEFAULT NULL COMMENT '其他综合收益',
  `oth_eqt_tools` varchar(64) DEFAULT NULL COMMENT '其他权益工具',
  `oth_eqt_tools_p_shr` varchar(64) DEFAULT NULL COMMENT '其他权益工具(优先股)',
  `lending_funds` varchar(64) DEFAULT NULL COMMENT '融出资金',
  `acc_receivable` varchar(64) DEFAULT NULL COMMENT '应收款项',
  `st_fin_payable` varchar(64) DEFAULT NULL COMMENT '应付短期融资款',
  `payables` varchar(64) DEFAULT NULL COMMENT '应付款项',
  `hfs_assets` varchar(64) DEFAULT NULL COMMENT '持有待售的资产',
  `hfs_sales` varchar(64) DEFAULT NULL COMMENT '持有待售的负债',
  `update_flag` varchar(64) DEFAULT NULL COMMENT '更新标识',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产负债表';

-- ----------------------------
-- Table structure for t_cash_flow
-- ----------------------------
DROP TABLE IF EXISTS `t_cash_flow`;
CREATE TABLE `t_cash_flow` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS股票代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `f_ann_date` varchar(64) DEFAULT NULL COMMENT '实际公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `comp_type` varchar(64) DEFAULT NULL COMMENT '报表类型',
  `report_type` varchar(64) DEFAULT NULL COMMENT '公司类型',
  `net_profit` varchar(64) DEFAULT NULL COMMENT '净利润',
  `finan_exp` varchar(64) DEFAULT NULL COMMENT '财务费用',
  `c_fr_sale_sg` varchar(64) DEFAULT NULL COMMENT '销售商品、提供劳务收到的现金',
  `recp_tax_rends` varchar(64) DEFAULT NULL COMMENT '收到的税费返还',
  `n_depos_incr_fi` varchar(64) DEFAULT NULL COMMENT '客户存款和同业存放款项净增加额',
  `n_incr_loans_cb` varchar(64) DEFAULT NULL COMMENT '向中央银行借款净增加额',
  `n_inc_borr_oth_fi` varchar(64) DEFAULT NULL COMMENT '向其他金融机构拆入资金净增加额',
  `prem_fr_orig_contr` varchar(64) DEFAULT NULL COMMENT '收到原保险合同保费取得的现金',
  `n_incr_insured_dep` varchar(64) DEFAULT NULL COMMENT '保户储金净增加额',
  `n_reinsur_prem` varchar(64) DEFAULT NULL COMMENT '收到再保业务现金净额',
  `n_incr_disp_tfa` varchar(64) DEFAULT NULL COMMENT '处置交易性金融资产净增加额',
  `ifc_cash_incr` varchar(64) DEFAULT NULL COMMENT '收取利息和手续费净增加额',
  `n_incr_disp_faas` varchar(64) DEFAULT NULL COMMENT '处置可供出售金融资产净增加额',
  `n_incr_loans_oth_bank` varchar(64) DEFAULT NULL COMMENT '拆入资金净增加额',
  `n_cap_incr_repur` varchar(64) DEFAULT NULL COMMENT '回购业务资金净增加额',
  `c_fr_oth_operate_a` varchar(64) DEFAULT NULL COMMENT '收到其他与经营活动有关的现金',
  `c_inf_fr_operate_a` varchar(64) DEFAULT NULL COMMENT '经营活动现金流入小计',
  `c_paid_goods_s` varchar(64) DEFAULT NULL COMMENT '购买商品、接受劳务支付的现金',
  `c_paid_to_for_empl` varchar(64) DEFAULT NULL COMMENT '支付给职工以及为职工支付的现金',
  `c_paid_for_taxes` varchar(64) DEFAULT NULL COMMENT '支付的各项税费',
  `n_incr_clt_loan_adv` varchar(64) DEFAULT NULL COMMENT '客户贷款及垫款净增加额',
  `n_incr_dep_cbob` varchar(64) DEFAULT NULL COMMENT '存放央行和同业款项净增加额',
  `c_pay_claims_orig_inco` varchar(64) DEFAULT NULL COMMENT '支付原保险合同赔付款项的现金',
  `pay_handling_chrg` varchar(64) DEFAULT NULL COMMENT '支付手续费的现金',
  `pay_comm_insur_plcy` varchar(64) DEFAULT NULL COMMENT '支付保单红利的现金',
  `oth_cash_pay_oper_act` varchar(64) DEFAULT NULL COMMENT '支付其他与经营活动有关的现金',
  `st_cash_out_act` varchar(64) DEFAULT NULL COMMENT '经营活动现金流出小计',
  `n_cashflow_act` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额',
  `oth_recp_ral_inv_act` varchar(64) DEFAULT NULL COMMENT '收到其他与投资活动有关的现金',
  `c_disp_withdrwl_invest` varchar(64) DEFAULT NULL COMMENT '收回投资收到的现金',
  `c_recp_return_invest` varchar(64) DEFAULT NULL COMMENT '取得投资收益收到的现金',
  `n_recp_disp_fiolta` varchar(64) DEFAULT NULL COMMENT '处置固定资产、无形资产和其他长期资产收回的现金净额',
  `n_recp_disp_sobu` varchar(64) DEFAULT NULL COMMENT '处置子公司及其他营业单位收到的现金净额',
  `stot_inflows_inv_act` varchar(64) DEFAULT NULL COMMENT '投资活动现金流入小计',
  `c_pay_acq_const_fiolta` varchar(64) DEFAULT NULL COMMENT '购建固定资产、无形资产和其他长期资产支付的现金',
  `c_paid_invest` varchar(64) DEFAULT NULL COMMENT '投资支付的现金',
  `n_disp_subs_oth_biz` varchar(64) DEFAULT NULL COMMENT '取得子公司及其他营业单位支付的现金净额',
  `oth_pay_ral_inv_act` varchar(64) DEFAULT NULL COMMENT '支付其他与投资活动有关的现金',
  `n_incr_pledge_loan` varchar(64) DEFAULT NULL COMMENT '质押贷款净增加额',
  `stot_out_inv_act` varchar(64) DEFAULT NULL COMMENT '投资活动现金流出小计',
  `n_cashflow_inv_act` varchar(64) DEFAULT NULL COMMENT '投资活动产生的现金流量净额',
  `c_recp_borrow` varchar(64) DEFAULT NULL COMMENT '取得借款收到的现金',
  `proc_issue_bonds` varchar(64) DEFAULT NULL COMMENT '发行债券收到的现金',
  `oth_cash_recp_ral_fnc_act` varchar(64) DEFAULT NULL COMMENT '收到其他与筹资活动有关的现金',
  `stot_cash_in_fnc_act` varchar(64) DEFAULT NULL COMMENT '筹资活动现金流入小计',
  `free_cashflow` varchar(64) DEFAULT NULL COMMENT '企业自由现金流量',
  `c_prepay_amt_borr` varchar(64) DEFAULT NULL COMMENT '偿还债务支付的现金',
  `c_pay_dist_dpcp_int_exp` varchar(64) DEFAULT NULL COMMENT '分配股利、利润或偿付利息支付的现金',
  `incl_dvd_profit_paid_sc_ms` varchar(64) DEFAULT NULL COMMENT '其中:子公司支付给少数股东的股利、利润',
  `oth_cashpay_ral_fnc_act` varchar(64) DEFAULT NULL COMMENT '支付其他与筹资活动有关的现金',
  `stot_cashout_fnc_act` varchar(64) DEFAULT NULL COMMENT '筹资活动现金流出小计',
  `n_cash_flows_fnc_act` varchar(64) DEFAULT NULL COMMENT '筹资活动产生的现金流量净额',
  `eff_fx_flu_cash` varchar(64) DEFAULT NULL COMMENT '汇率变动对现金的影响',
  `n_incr_cash_cash_equ` varchar(64) DEFAULT NULL COMMENT '现金及现金等价物净增加额',
  `c_cash_equ_beg_period` varchar(64) DEFAULT NULL COMMENT '期初现金及现金等价物余额',
  `c_cash_equ_end_period` varchar(64) DEFAULT NULL COMMENT '期末现金及现金等价物余额',
  `c_recp_cap_contrib` varchar(64) DEFAULT NULL COMMENT '吸收投资收到的现金',
  `incl_cash_rec_saims` varchar(64) DEFAULT NULL COMMENT '其中:子公司吸收少数股东投资收到的现金',
  `uncon_invest_loss` varchar(64) DEFAULT NULL COMMENT '未确认投资损失',
  `prov_depr_assets` varchar(64) DEFAULT NULL COMMENT '加:资产减值准备',
  `depr_fa_coga_dpba` varchar(64) DEFAULT NULL COMMENT '固定资产折旧、油气资产折耗、生产性生物资产折旧',
  `amort_intang_assets` varchar(64) DEFAULT NULL COMMENT '无形资产摊销',
  `lt_amort_deferred_exp` varchar(64) DEFAULT NULL COMMENT '长期待摊费用摊销',
  `decr_deferred_exp` varchar(64) DEFAULT NULL COMMENT '待摊费用减少',
  `incr_acc_exp` varchar(64) DEFAULT NULL COMMENT '预提费用增加',
  `loss_disp_fiolta` varchar(64) DEFAULT NULL COMMENT '处置固定、无形资产和其他长期资产的损失',
  `loss_scr_fa` varchar(64) DEFAULT NULL COMMENT '固定资产报废损失',
  `loss_fv_chg` varchar(64) DEFAULT NULL COMMENT '公允价值变动损失',
  `invest_loss` varchar(64) DEFAULT NULL COMMENT '投资损失',
  `decr_def_inc_tax_assets` varchar(64) DEFAULT NULL COMMENT '递延所得税资产减少',
  `incr_def_inc_tax_liab` varchar(64) DEFAULT NULL COMMENT '递延所得税负债增加',
  `decr_inventories` varchar(64) DEFAULT NULL COMMENT '存货的减少',
  `decr_oper_payable` varchar(64) DEFAULT NULL COMMENT '经营性应收项目的减少',
  `incr_oper_payable` varchar(64) DEFAULT NULL COMMENT '经营性应付项目的增加',
  `others` varchar(64) DEFAULT NULL COMMENT '其他',
  `im_net_cashflow_oper_act` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额(间接法)',
  `conv_debt_into_cap` varchar(64) DEFAULT NULL COMMENT '债务转为资本',
  `conv_copbonds_due_within_1y` varchar(64) DEFAULT NULL COMMENT '一年内到期的可转换公司债券',
  `fa_fnc_leases` varchar(64) DEFAULT NULL COMMENT '融资租入固定资产',
  `end_bal_cash` varchar(64) DEFAULT NULL COMMENT '现金的期末余额',
  `beg_bal_cash` varchar(64) DEFAULT NULL COMMENT '减:现金的期初余额',
  `end_bal_cash_equ` varchar(64) DEFAULT NULL COMMENT '加:现金等价物的期末余额',
  `beg_bal_cash_equ` varchar(64) DEFAULT NULL COMMENT '减:现金等价物的期初余额',
  `im_n_incr_cash_equ` varchar(64) DEFAULT NULL COMMENT '现金及现金等价物净增加额(间接法)',
  `update_flag` varchar(64) DEFAULT NULL COMMENT '更新标识',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='现金流量表';

-- ----------------------------
-- Table structure for t_disclosure_date
-- ----------------------------
DROP TABLE IF EXISTS `t_disclosure_date`;
CREATE TABLE `t_disclosure_date` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '最新披露公告日',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `pre_date` varchar(64) DEFAULT NULL COMMENT '预计披露日期',
  `actual_date` varchar(64) DEFAULT NULL COMMENT '实际披露日期',
  `modify_date` varchar(64) DEFAULT NULL COMMENT '披露日期修正记录',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财报披露计划';

-- ----------------------------
-- Table structure for t_dividend
-- ----------------------------
DROP TABLE IF EXISTS `t_dividend`;
CREATE TABLE `t_dividend` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS代码',
  `end_date` varchar(64) DEFAULT NULL COMMENT '分红年度',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '预案公告日',
  `div_proc` varchar(64) DEFAULT NULL COMMENT '实施进度',
  `stk_div` varchar(64) DEFAULT NULL COMMENT '每股送转',
  `stk_bo_rate` varchar(64) DEFAULT NULL COMMENT '每股送股比例',
  `stk_co_rate` varchar(64) DEFAULT NULL COMMENT '每股转增比例',
  `cash_div` varchar(64) DEFAULT NULL COMMENT '每股分红（税后）',
  `cash_div_tax` varchar(64) DEFAULT NULL COMMENT '每股分红（税前）',
  `record_date` varchar(64) DEFAULT NULL COMMENT '股权登记日',
  `ex_date` varchar(64) DEFAULT NULL COMMENT '除权除息日',
  `pay_date` varchar(64) DEFAULT NULL COMMENT '派息日',
  `div_listdate` varchar(64) DEFAULT NULL COMMENT '红股上市日',
  `imp_ann_date` varchar(64) DEFAULT NULL COMMENT '实施公告日',
  `base_date` varchar(64) DEFAULT NULL COMMENT '基准日',
  `base_share` varchar(64) DEFAULT NULL COMMENT '基准股本（万）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分红送股';

-- ----------------------------
-- Table structure for t_express
-- ----------------------------
DROP TABLE IF EXISTS `t_express`;
CREATE TABLE `t_express` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS股票代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `revenue` varchar(64) DEFAULT NULL COMMENT '营业收入(元)',
  `operate_profit` varchar(64) DEFAULT NULL COMMENT '营业利润(元)',
  `total_profit` varchar(64) DEFAULT NULL COMMENT '利润总额(元)',
  `n_income` varchar(64) DEFAULT NULL COMMENT '净利润(元)',
  `total_assets` varchar(64) DEFAULT NULL COMMENT '总资产(元)',
  `total_hldr_eqy_exc_min_int` varchar(64) DEFAULT NULL COMMENT '股东权益合计(不含少数股东权益)(元)',
  `diluted_eps` varchar(64) DEFAULT NULL COMMENT '每股收益(摊薄)(元)',
  `diluted_roe` varchar(64) DEFAULT NULL COMMENT '净资产收益率(摊薄)(%)',
  `yoy_net_profit` varchar(64) DEFAULT NULL COMMENT '去年同期修正后净利润',
  `bps` varchar(64) DEFAULT NULL COMMENT '每股净资产',
  `yoy_sales` varchar(64) DEFAULT NULL COMMENT '同比增长率:营业收入',
  `yoy_op` varchar(64) DEFAULT NULL COMMENT '同比增长率:营业利润',
  `yoy_tp` varchar(64) DEFAULT NULL COMMENT '同比增长率:利润总额',
  `yoy_dedu_np` varchar(64) DEFAULT NULL COMMENT '同比增长率:归属母公司股东的净利润',
  `yoy_eps` varchar(64) DEFAULT NULL COMMENT '同比增长率:基本每股收益',
  `yoy_roe` varchar(64) DEFAULT NULL COMMENT '同比增减:加权平均净资产收益率',
  `growth_assets` varchar(64) DEFAULT NULL COMMENT '比年初增长率:总资产',
  `yoy_equity` varchar(64) DEFAULT NULL COMMENT '比年初增长率:归属母公司的股东权益',
  `growth_bps` varchar(64) DEFAULT NULL COMMENT '比年初增长率:归属于母公司股东的每股净资产',
  `or_last_year` varchar(64) DEFAULT NULL COMMENT '去年同期营业收入',
  `op_last_year` varchar(64) DEFAULT NULL COMMENT '去年同期营业利润',
  `tp_last_year` varchar(64) DEFAULT NULL COMMENT '去年同期利润总额',
  `np_last_year` varchar(64) DEFAULT NULL COMMENT '去年同期净利润',
  `eps_last_year` varchar(64) DEFAULT NULL COMMENT '去年同期每股收益',
  `open_net_assets` varchar(64) DEFAULT NULL COMMENT '期初净资产',
  `open_bps` varchar(64) DEFAULT NULL COMMENT '期初每股净资产',
  `perf_summary` varchar(64) DEFAULT NULL COMMENT '业绩简要说明',
  `is_audit` varchar(64) DEFAULT NULL COMMENT '是否审计： 1是 0否',
  `remark` varchar(64) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业绩快报';

-- ----------------------------
-- Table structure for t_fina_audit
-- ----------------------------
DROP TABLE IF EXISTS `t_fina_audit`;
CREATE TABLE `t_fina_audit` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS股票代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `audit_result` varchar(64) DEFAULT NULL COMMENT '审计结果',
  `audit_fees` varchar(64) DEFAULT NULL COMMENT '审计总费用（元）',
  `audit_agency` varchar(64) DEFAULT NULL COMMENT '会计事务所',
  `audit_sign` varchar(64) DEFAULT NULL COMMENT '签字会计师',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务审计意见';

-- ----------------------------
-- Table structure for t_fina_indicator
-- ----------------------------
DROP TABLE IF EXISTS `t_fina_indicator`;
CREATE TABLE `t_fina_indicator` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `eps` varchar(64) DEFAULT NULL COMMENT '基本每股收益',
  `dt_eps` varchar(64) DEFAULT NULL COMMENT '稀释每股收益',
  `total_revenue_ps` varchar(64) DEFAULT NULL COMMENT '每股营业总收入',
  `revenue_ps` varchar(64) DEFAULT NULL COMMENT '每股营业收入',
  `capital_rese_ps` varchar(64) DEFAULT NULL COMMENT '每股资本公积',
  `surplus_rese_ps` varchar(64) DEFAULT NULL COMMENT '每股盈余公积',
  `undist_profit_ps` varchar(64) DEFAULT NULL COMMENT '每股未分配利润',
  `extra_item` varchar(64) DEFAULT NULL COMMENT '非经常性损益',
  `profit_dedt` varchar(64) DEFAULT NULL COMMENT '扣除非经常性损益后的净利润',
  `gross_margin` varchar(64) DEFAULT NULL COMMENT '毛利',
  `current_ratio` varchar(64) DEFAULT NULL COMMENT '流动比率',
  `quick_ratio` varchar(64) DEFAULT NULL COMMENT '速动比率',
  `cash_ratio` varchar(64) DEFAULT NULL COMMENT '保守速动比率',
  `invturn_days` varchar(64) DEFAULT NULL COMMENT '存货周转天数',
  `arturn_days` varchar(64) DEFAULT NULL COMMENT '应收账款周转天数',
  `inv_turn` varchar(64) DEFAULT NULL COMMENT '存货周转率',
  `ar_turn` varchar(64) DEFAULT NULL COMMENT '应收账款周转率',
  `ca_turn` varchar(64) DEFAULT NULL COMMENT '流动资产周转率',
  `fa_turn` varchar(64) DEFAULT NULL COMMENT '固定资产周转率',
  `assets_turn` varchar(64) DEFAULT NULL COMMENT '总资产周转率',
  `op_income` varchar(64) DEFAULT NULL COMMENT '经营活动净收益',
  `valuechange_income` varchar(64) DEFAULT NULL COMMENT '价值变动净收益',
  `interst_income` varchar(64) DEFAULT NULL COMMENT '利息费用',
  `daa` varchar(64) DEFAULT NULL COMMENT '折旧与摊销',
  `ebit` varchar(64) DEFAULT NULL COMMENT '息税前利润',
  `ebitda` varchar(64) DEFAULT NULL COMMENT '息税折旧摊销前利润',
  `fcff` varchar(64) DEFAULT NULL COMMENT '企业自由现金流量',
  `fcfe` varchar(64) DEFAULT NULL COMMENT '股权自由现金流量',
  `current_exint` varchar(64) DEFAULT NULL COMMENT '无息流动负债',
  `noncurrent_exint` varchar(64) DEFAULT NULL COMMENT '无息非流动负债',
  `interestdebt` varchar(64) DEFAULT NULL COMMENT '带息债务',
  `netdebt` varchar(64) DEFAULT NULL COMMENT '净债务',
  `tangible_asset` varchar(64) DEFAULT NULL COMMENT '有形资产',
  `working_capital` varchar(64) DEFAULT NULL COMMENT '营运资金',
  `networking_capital` varchar(64) DEFAULT NULL COMMENT '营运流动资本',
  `invest_capital` varchar(64) DEFAULT NULL COMMENT '全部投入资本',
  `retained_earnings` varchar(64) DEFAULT NULL COMMENT '留存收益',
  `diluted2_eps` varchar(64) DEFAULT NULL COMMENT '期末摊薄每股收益',
  `bps` varchar(64) DEFAULT NULL COMMENT '每股净资产',
  `ocfps` varchar(64) DEFAULT NULL COMMENT '每股经营活动产生的现金流量净额',
  `retainedps` varchar(64) DEFAULT NULL COMMENT '每股留存收益',
  `cfps` varchar(64) DEFAULT NULL COMMENT '每股现金流量净额',
  `ebit_ps` varchar(64) DEFAULT NULL COMMENT '每股息税前利润',
  `fcff_ps` varchar(64) DEFAULT NULL COMMENT '每股企业自由现金流量',
  `fcfe_ps` varchar(64) DEFAULT NULL COMMENT '每股股东自由现金流量',
  `netprofit_margin` varchar(64) DEFAULT NULL COMMENT '销售净利率',
  `grossprofit_margin` varchar(64) DEFAULT NULL COMMENT '销售毛利率',
  `cogs_of_sales` varchar(64) DEFAULT NULL COMMENT '销售成本率',
  `expense_of_sales` varchar(64) DEFAULT NULL COMMENT '销售期间费用率',
  `profit_to_gr` varchar(64) DEFAULT NULL COMMENT '净利润/营业总收入',
  `saleexp_to_gr` varchar(64) DEFAULT NULL COMMENT '销售费用/营业总收入',
  `adminexp_of_gr` varchar(64) DEFAULT NULL COMMENT '管理费用/营业总收入',
  `finaexp_of_gr` varchar(64) DEFAULT NULL COMMENT '财务费用/营业总收入',
  `impai_ttm` varchar(64) DEFAULT NULL COMMENT '资产减值损失/营业总收入',
  `gc_of_gr` varchar(64) DEFAULT NULL COMMENT '营业总成本/营业总收入',
  `op_of_gr` varchar(64) DEFAULT NULL COMMENT '营业利润/营业总收入',
  `ebit_of_gr` varchar(64) DEFAULT NULL COMMENT '息税前利润/营业总收入',
  `roe` varchar(64) DEFAULT NULL COMMENT '净资产收益率',
  `roe_waa` varchar(64) DEFAULT NULL COMMENT '加权平均净资产收益率',
  `roe_dt` varchar(64) DEFAULT NULL COMMENT '净资产收益率(扣除非经常损益)',
  `roa` varchar(64) DEFAULT NULL COMMENT '总资产报酬率',
  `npta` varchar(64) DEFAULT NULL COMMENT '总资产净利润',
  `roic` varchar(64) DEFAULT NULL COMMENT '投入资本回报率',
  `roe_yearly` varchar(64) DEFAULT NULL COMMENT '年化净资产收益率',
  `roa2_yearly` varchar(64) DEFAULT NULL COMMENT '年化总资产报酬率',
  `roe_avg` varchar(64) DEFAULT NULL COMMENT '平均净资产收益率(增发条件)',
  `opincome_of_ebt` varchar(64) DEFAULT NULL COMMENT '经营活动净收益/利润总额',
  `investincome_of_ebt` varchar(64) DEFAULT NULL COMMENT '价值变动净收益/利润总额',
  `n_op_profit_of_ebt` varchar(64) DEFAULT NULL COMMENT '营业外收支净额/利润总额',
  `tax_to_ebt` varchar(64) DEFAULT NULL COMMENT '所得税/利润总额',
  `dtprofit_to_profit` varchar(64) DEFAULT NULL COMMENT '扣除非经常损益后的净利润/净利润',
  `salescash_to_or` varchar(64) DEFAULT NULL COMMENT '销售商品提供劳务收到的现金/营业收入',
  `ocf_to_or` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额/营业收入',
  `ocf_to_opincome` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额/经营活动净收益',
  `capitalized_to_da` varchar(64) DEFAULT NULL COMMENT '资本支出/折旧和摊销',
  `debt_to_assets` varchar(64) DEFAULT NULL COMMENT '资产负债率',
  `assets_to_eqt` varchar(64) DEFAULT NULL COMMENT '权益乘数',
  `dp_assets_to_eqt` varchar(64) DEFAULT NULL COMMENT '权益乘数(杜邦分析)',
  `ca_to_assets` varchar(64) DEFAULT NULL COMMENT '流动资产/总资产',
  `nca_to_assets` varchar(64) DEFAULT NULL COMMENT '非流动资产/总资产',
  `tbassets_to_totalassets` varchar(64) DEFAULT NULL COMMENT '有形资产/总资产',
  `int_to_talcap` varchar(64) DEFAULT NULL COMMENT '带息债务/全部投入资本',
  `eqt_to_talcapital` varchar(64) DEFAULT NULL COMMENT '归属于母公司的股东权益/全部投入资本',
  `currentdebt_to_debt` varchar(64) DEFAULT NULL COMMENT '流动负债/负债合计',
  `longdeb_to_debt` varchar(64) DEFAULT NULL COMMENT '非流动负债/负债合计',
  `ocf_to_shortdebt` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额/流动负债',
  `debt_to_eqt` varchar(64) DEFAULT NULL COMMENT '产权比率',
  `eqt_to_debt` varchar(64) DEFAULT NULL COMMENT '归属于母公司的股东权益/负债合计',
  `eqt_to_interestdebt` varchar(64) DEFAULT NULL COMMENT '归属于母公司的股东权益/带息债务',
  `tangibleasset_to_debt` varchar(64) DEFAULT NULL COMMENT '有形资产/负债合计',
  `tangasset_to_intdebt` varchar(64) DEFAULT NULL COMMENT '有形资产/带息债务',
  `tangibleasset_to_netdebt` varchar(64) DEFAULT NULL COMMENT '有形资产/净债务',
  `ocf_to_debt` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额/负债合计',
  `ocf_to_interestdebt` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额/带息债务',
  `ocf_to_netdebt` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额/净债务',
  `ebit_to_interest` varchar(64) DEFAULT NULL COMMENT '已获利息倍数(EBIT/利息费用)',
  `longdebt_to_workingcapital` varchar(64) DEFAULT NULL COMMENT '长期债务与营运资金比率',
  `ebitda_to_debt` varchar(64) DEFAULT NULL COMMENT '息税折旧摊销前利润/负债合计',
  `turn_days` varchar(64) DEFAULT NULL COMMENT '营业周期',
  `roa_yearly` varchar(64) DEFAULT NULL COMMENT '年化总资产净利率',
  `roa_dp` varchar(64) DEFAULT NULL COMMENT '总资产净利率(杜邦分析)',
  `fixed_assets` varchar(64) DEFAULT NULL COMMENT '固定资产合计',
  `profit_prefin_exp` varchar(64) DEFAULT NULL COMMENT '扣除财务费用前营业利润',
  `non_op_profit` varchar(64) DEFAULT NULL COMMENT '非营业利润',
  `op_to_ebt` varchar(64) DEFAULT NULL COMMENT '营业利润／利润总额',
  `nop_to_ebt` varchar(64) DEFAULT NULL COMMENT '非营业利润／利润总额',
  `ocf_to_profit` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额／营业利润',
  `cash_to_liqdebt` varchar(64) DEFAULT NULL COMMENT '货币资金／流动负债',
  `cash_to_liqdebt_withinterest` varchar(64) DEFAULT NULL COMMENT '货币资金／带息流动负债',
  `op_to_liqdebt` varchar(64) DEFAULT NULL COMMENT '营业利润／流动负债',
  `op_to_debt` varchar(64) DEFAULT NULL COMMENT '营业利润／负债合计',
  `roic_yearly` varchar(64) DEFAULT NULL COMMENT '年化投入资本回报率',
  `total_fa_trun` varchar(64) DEFAULT NULL COMMENT '固定资产合计周转率',
  `profit_to_op` varchar(64) DEFAULT NULL COMMENT '利润总额／营业收入',
  `q_opincome` varchar(64) DEFAULT NULL COMMENT '经营活动单季度净收益',
  `q_investincome` varchar(64) DEFAULT NULL COMMENT '价值变动单季度净收益',
  `q_dtprofit` varchar(64) DEFAULT NULL COMMENT '扣除非经常损益后的单季度净利润',
  `q_eps` varchar(64) DEFAULT NULL COMMENT '每股收益(单季度)',
  `q_netprofit_margin` varchar(64) DEFAULT NULL COMMENT '销售净利率(单季度)',
  `q_gsprofit_margin` varchar(64) DEFAULT NULL COMMENT '销售毛利率(单季度)',
  `q_exp_to_sales` varchar(64) DEFAULT NULL COMMENT '销售期间费用率(单季度)',
  `q_profit_to_gr` varchar(64) DEFAULT NULL COMMENT '净利润／营业总收入(单季度)',
  `q_saleexp_to_gr` varchar(64) DEFAULT NULL COMMENT '销售费用／营业总收入 (单季度)',
  `q_adminexp_to_gr` varchar(64) DEFAULT NULL COMMENT '管理费用／营业总收入 (单季度)',
  `q_finaexp_to_gr` varchar(64) DEFAULT NULL COMMENT '财务费用／营业总收入 (单季度)',
  `q_impair_to_gr_ttm` varchar(64) DEFAULT NULL COMMENT '资产减值损失／营业总收入(单季度)',
  `q_gc_to_gr` varchar(64) DEFAULT NULL COMMENT '营业总成本／营业总收入 (单季度)',
  `q_op_to_gr` varchar(64) DEFAULT NULL COMMENT '营业利润／营业总收入(单季度)',
  `q_roe` varchar(64) DEFAULT NULL COMMENT '净资产收益率(单季度)',
  `q_dt_roe` varchar(64) DEFAULT NULL COMMENT '净资产单季度收益率(扣除非经常损益)',
  `q_npta` varchar(64) DEFAULT NULL COMMENT '总资产净利润(单季度)',
  `q_opincome_to_ebt` varchar(64) DEFAULT NULL COMMENT '经营活动净收益／利润总额(单季度)',
  `q_investincome_to_ebt` varchar(64) DEFAULT NULL COMMENT '价值变动净收益／利润总额(单季度)',
  `q_dtprofit_to_profit` varchar(64) DEFAULT NULL COMMENT '扣除非经常损益后的净利润／净利润(单季度)',
  `q_salescash_to_or` varchar(64) DEFAULT NULL COMMENT '销售商品提供劳务收到的现金／营业收入(单季度)',
  `q_ocf_to_sales` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额／营业收入(单季度)',
  `q_ocf_to_or` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额／经营活动净收益(单季度)',
  `basic_eps_yoy` varchar(64) DEFAULT NULL COMMENT '基本每股收益同比增长率(%)',
  `dt_eps_yoy` varchar(64) DEFAULT NULL COMMENT '稀释每股收益同比增长率(%)',
  `cfps_yoy` varchar(64) DEFAULT NULL COMMENT '每股经营活动产生的现金流量净额同比增长率(%)',
  `op_yoy` varchar(64) DEFAULT NULL COMMENT '营业利润同比增长率(%)',
  `ebt_yoy` varchar(64) DEFAULT NULL COMMENT '利润总额同比增长率(%)',
  `netprofit_yoy` varchar(64) DEFAULT NULL COMMENT '归属母公司股东的净利润同比增长率(%)',
  `dt_netprofit_yoy` varchar(64) DEFAULT NULL COMMENT '归属母公司股东的净利润-扣除非经常损益同比增长率(%)',
  `ocf_yoy` varchar(64) DEFAULT NULL COMMENT '经营活动产生的现金流量净额同比增长率(%)',
  `roe_yoy` varchar(64) DEFAULT NULL COMMENT '净资产收益率(摊薄)同比增长率(%)',
  `bps_yoy` varchar(64) DEFAULT NULL COMMENT '每股净资产相对年初增长率(%)',
  `assets_yoy` varchar(64) DEFAULT NULL COMMENT '资产总计相对年初增长率(%)',
  `eqt_yoy` varchar(64) DEFAULT NULL COMMENT '归属母公司的股东权益相对年初增长率(%)',
  `tr_yoy` varchar(64) DEFAULT NULL COMMENT '营业总收入同比增长率(%)',
  `or_yoy` varchar(64) DEFAULT NULL COMMENT '营业收入同比增长率(%)',
  `q_gr_yoy` varchar(64) DEFAULT NULL COMMENT '营业总收入同比增长率(%)(单季度)',
  `q_gr_qoq` varchar(64) DEFAULT NULL COMMENT '营业总收入环比增长率(%)(单季度)',
  `q_sales_yoy` varchar(64) DEFAULT NULL COMMENT '营业收入同比增长率(%)(单季度)',
  `q_sales_qoq` varchar(64) DEFAULT NULL COMMENT '营业收入环比增长率(%)(单季度)',
  `q_op_yoy` varchar(64) DEFAULT NULL COMMENT '营业利润同比增长率(%)(单季度)',
  `q_op_qoq` varchar(64) DEFAULT NULL COMMENT '营业利润环比增长率(%)(单季度)',
  `q_profit_yoy` varchar(64) DEFAULT NULL COMMENT '净利润同比增长率(%)(单季度)',
  `q_profit_qoq` varchar(64) DEFAULT NULL COMMENT '净利润环比增长率(%)(单季度)',
  `q_netprofit_yoy` varchar(64) DEFAULT NULL COMMENT '归属母公司股东的净利润同比增长率(%)(单季度)',
  `q_netprofit_qoq` varchar(64) DEFAULT NULL COMMENT '归属母公司股东的净利润环比增长率(%)(单季度)',
  `equity_yoy` varchar(64) DEFAULT NULL COMMENT '净资产同比增长率',
  `rd_exp` varchar(64) DEFAULT NULL COMMENT '研发费用',
  `update_flag` varchar(64) DEFAULT NULL COMMENT '更新标识',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务指标数据';

-- ----------------------------
-- Table structure for t_fina_mainbz
-- ----------------------------
DROP TABLE IF EXISTS `t_fina_mainbz`;
CREATE TABLE `t_fina_mainbz` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS代码',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `bz_item` varchar(64) DEFAULT NULL COMMENT '主营业务来源',
  `bz_sales` varchar(64) DEFAULT NULL COMMENT '主营业务收入(元)',
  `bz_profit` varchar(64) DEFAULT NULL COMMENT '主营业务利润(元)',
  `bz_cost` varchar(64) DEFAULT NULL COMMENT '主营业务成本(元)',
  `curr_type` varchar(64) DEFAULT NULL COMMENT '货币代码',
  `update_flag` varchar(64) DEFAULT NULL COMMENT '是否更新',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='主营业务构成';

-- ----------------------------
-- Table structure for t_forecast
-- ----------------------------
DROP TABLE IF EXISTS `t_forecast`;
CREATE TABLE `t_forecast` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS股票代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `type` varchar(64) DEFAULT NULL COMMENT '业绩预告类型(预增/预减/扭亏/首亏/续亏/续盈/略增/略减)',
  `p_change_min` varchar(64) DEFAULT NULL COMMENT '预告净利润变动幅度下限（%）',
  `p_change_max` varchar(64) DEFAULT NULL COMMENT '预告净利润变动幅度上限（%）',
  `net_profit_min` varchar(64) DEFAULT NULL COMMENT '预告净利润下限（万元）',
  `net_profit_max` varchar(64) DEFAULT NULL COMMENT '预告净利润上限（万元）',
  `last_parent_net` varchar(64) DEFAULT NULL COMMENT '上年同期归属母公司净利润',
  `first_ann_date` varchar(64) DEFAULT NULL COMMENT '首次公告日',
  `summary` varchar(64) DEFAULT NULL COMMENT '业绩预告摘要',
  `change_reason` varchar(64) DEFAULT NULL COMMENT '业绩变动原因',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业绩预告';

-- ----------------------------
-- Table structure for t_income
-- ----------------------------
DROP TABLE IF EXISTS `t_income`;
CREATE TABLE `t_income` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `f_ann_date` varchar(64) DEFAULT NULL COMMENT '实际公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `report_type` varchar(64) DEFAULT NULL COMMENT '报告类型 1合并报表 2单季合并 3调整单季合并表 4调整合并报表 5调整前合并报表 6母公司报表 7母公司单季表 8 母公司调整单季表 9母公司调整表 10母公司调整前报表 11调整前合并报表 12母公司调整前报表',
  `comp_type` varchar(64) DEFAULT NULL COMMENT '公司类型(1一般工商业2银行3保险4证券)',
  `basic_eps` varchar(64) DEFAULT NULL COMMENT '基本每股收益',
  `diluted_eps` varchar(64) DEFAULT NULL COMMENT '稀释每股收益',
  `total_revenue` varchar(64) DEFAULT NULL COMMENT '营业总收入',
  `revenue` varchar(64) DEFAULT NULL COMMENT '营业收入',
  `int_income` varchar(64) DEFAULT NULL COMMENT '利息收入',
  `prem_earned` varchar(64) DEFAULT NULL COMMENT '已赚保费',
  `comm_income` varchar(64) DEFAULT NULL COMMENT '手续费及佣金收入',
  `n_commis_income` varchar(64) DEFAULT NULL COMMENT '手续费及佣金净收入',
  `n_oth_income` varchar(64) DEFAULT NULL COMMENT '其他经营净收益',
  `n_oth_b_income` varchar(64) DEFAULT NULL COMMENT '加:其他业务净收益',
  `prem_income` varchar(64) DEFAULT NULL COMMENT '保险业务收入',
  `out_prem` varchar(64) DEFAULT NULL COMMENT '减:分出保费',
  `une_prem_reser` varchar(64) DEFAULT NULL COMMENT '提取未到期责任准备金',
  `reins_income` varchar(64) DEFAULT NULL COMMENT '其中:分保费收入',
  `n_sec_tb_income` varchar(64) DEFAULT NULL COMMENT '代理买卖证券业务净收入',
  `n_sec_uw_income` varchar(64) DEFAULT NULL COMMENT '证券承销业务净收入',
  `n_asset_mg_income` varchar(64) DEFAULT NULL COMMENT '受托客户资产管理业务净收入',
  `oth_b_income` varchar(64) DEFAULT NULL COMMENT '其他业务收入',
  `fv_value_chg_gain` varchar(64) DEFAULT NULL COMMENT '加:公允价值变动净收益',
  `invest_income` varchar(64) DEFAULT NULL COMMENT '加:投资净收益',
  `ass_invest_income` varchar(64) DEFAULT NULL COMMENT '其中:对联营企业和合营企业的投资收益',
  `forex_gain` varchar(64) DEFAULT NULL COMMENT '加:汇兑净收益',
  `total_cogs` varchar(64) DEFAULT NULL COMMENT '营业总成本',
  `oper_cost` varchar(64) DEFAULT NULL COMMENT '减:营业成本',
  `int_exp` varchar(64) DEFAULT NULL COMMENT '减:利息支出',
  `comm_exp` varchar(64) DEFAULT NULL COMMENT '减:手续费及佣金支出',
  `biz_tax_surchg` varchar(64) DEFAULT NULL COMMENT '减:营业税金及附加',
  `sell_exp` varchar(64) DEFAULT NULL COMMENT '减:销售费用',
  `admin_exp` varchar(64) DEFAULT NULL COMMENT '减:管理费用',
  `fin_exp` varchar(64) DEFAULT NULL COMMENT '减:财务费用',
  `assets_impair_loss` varchar(64) DEFAULT NULL COMMENT '减:资产减值损失',
  `prem_refund` varchar(64) DEFAULT NULL COMMENT '退保金',
  `compens_payout` varchar(64) DEFAULT NULL COMMENT '赔付总支出',
  `reser_insur_liab` varchar(64) DEFAULT NULL COMMENT '提取保险责任准备金',
  `div_payt` varchar(64) DEFAULT NULL COMMENT '保户红利支出',
  `reins_exp` varchar(64) DEFAULT NULL COMMENT '分保费用',
  `oper_exp` varchar(64) DEFAULT NULL COMMENT '营业支出',
  `compens_payout_refu` varchar(64) DEFAULT NULL COMMENT '减:摊回赔付支出',
  `insur_reser_refu` varchar(64) DEFAULT NULL COMMENT '减:摊回保险责任准备金',
  `reins_cost_refund` varchar(64) DEFAULT NULL COMMENT '减:摊回分保费用',
  `other_bus_cost` varchar(64) DEFAULT NULL COMMENT '其他业务成本',
  `operate_profit` varchar(64) DEFAULT NULL COMMENT '营业利润',
  `non_oper_income` varchar(64) DEFAULT NULL COMMENT '加:营业外收入',
  `non_oper_exp` varchar(64) DEFAULT NULL COMMENT '减:营业外支出',
  `nca_disploss` varchar(64) DEFAULT NULL COMMENT '其中:减:非流动资产处置净损失',
  `total_profit` varchar(64) DEFAULT NULL COMMENT '利润总额',
  `income_tax` varchar(64) DEFAULT NULL COMMENT '所得税费用',
  `n_income` varchar(64) DEFAULT NULL COMMENT '净利润(含少数股东损益)',
  `n_income_attr_p` varchar(64) DEFAULT NULL COMMENT '净利润(不含少数股东损益)',
  `minority_gain` varchar(64) DEFAULT NULL COMMENT '少数股东损益',
  `oth_compr_income` varchar(64) DEFAULT NULL COMMENT '其他综合收益',
  `t_compr_income` varchar(64) DEFAULT NULL COMMENT '综合收益总额',
  `compr_inc_attr_p` varchar(64) DEFAULT NULL COMMENT '归属于母公司(或股东)的综合收益总额',
  `compr_inc_attr_m_s` varchar(64) DEFAULT NULL COMMENT '归属于少数股东的综合收益总额',
  `ebit` varchar(64) DEFAULT NULL COMMENT '息税前利润',
  `ebitda` varchar(64) DEFAULT NULL COMMENT '息税折旧摊销前利润',
  `insurance_exp` varchar(64) DEFAULT NULL COMMENT '保险业务支出',
  `undist_profit` varchar(64) DEFAULT NULL COMMENT '年初未分配利润',
  `distable_profit` varchar(64) DEFAULT NULL COMMENT '可分配利润',
  `update_flag` varchar(64) DEFAULT NULL COMMENT '更新标识',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='利润表';

-- ----------------------------
-- Table structure for t_news
-- ----------------------------
DROP TABLE IF EXISTS `t_news`;
CREATE TABLE `t_news` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `news_datetime` datetime DEFAULT NULL COMMENT '新闻时间',
  `content` text COMMENT '内容',
  `title` varchar(128) DEFAULT NULL COMMENT '标题',
  `channels` varchar(32) DEFAULT NULL COMMENT '分类',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='新闻资讯';

-- ----------------------------
-- Table structure for t_top10_float_holders
-- ----------------------------
DROP TABLE IF EXISTS `t_top10_float_holders`;
CREATE TABLE `t_top10_float_holders` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS股票代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `holder_name` varchar(64) DEFAULT NULL COMMENT '股东名称',
  `hold_amount` varchar(64) DEFAULT NULL COMMENT '持有数量（股）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='前十大流通股东';

-- ----------------------------
-- Table structure for t_top10_holders
-- ----------------------------
DROP TABLE IF EXISTS `t_top10_holders`;
CREATE TABLE `t_top10_holders` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts_code` varchar(64) DEFAULT NULL COMMENT 'TS股票代码',
  `ann_date` varchar(64) DEFAULT NULL COMMENT '公告日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '报告期',
  `holder_name` varchar(64) DEFAULT NULL COMMENT '股东名称',
  `hold_amount` varchar(64) DEFAULT NULL COMMENT '持有数量（股）',
  `hold_ratio` varchar(64) DEFAULT NULL COMMENT '持有比例',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='前十大股东';

SET FOREIGN_KEY_CHECKS = 1;
