package com.yskj.push.domain;

import java.util.Date;

public class CashFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.f_ann_date
     *
     * @mbggenerated
     */
    private String fAnnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.comp_type
     *
     * @mbggenerated
     */
    private String compType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.report_type
     *
     * @mbggenerated
     */
    private String reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.net_profit
     *
     * @mbggenerated
     */
    private String netProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.finan_exp
     *
     * @mbggenerated
     */
    private String finanExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_fr_sale_sg
     *
     * @mbggenerated
     */
    private String cFrSaleSg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.recp_tax_rends
     *
     * @mbggenerated
     */
    private String recpTaxRends;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_depos_incr_fi
     *
     * @mbggenerated
     */
    private String nDeposIncrFi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_loans_cb
     *
     * @mbggenerated
     */
    private String nIncrLoansCb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_inc_borr_oth_fi
     *
     * @mbggenerated
     */
    private String nIncBorrOthFi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.prem_fr_orig_contr
     *
     * @mbggenerated
     */
    private String premFrOrigContr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_insured_dep
     *
     * @mbggenerated
     */
    private String nIncrInsuredDep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_reinsur_prem
     *
     * @mbggenerated
     */
    private String nReinsurPrem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_disp_tfa
     *
     * @mbggenerated
     */
    private String nIncrDispTfa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.ifc_cash_incr
     *
     * @mbggenerated
     */
    private String ifcCashIncr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_disp_faas
     *
     * @mbggenerated
     */
    private String nIncrDispFaas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_loans_oth_bank
     *
     * @mbggenerated
     */
    private String nIncrLoansOthBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_cap_incr_repur
     *
     * @mbggenerated
     */
    private String nCapIncrRepur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_fr_oth_operate_a
     *
     * @mbggenerated
     */
    private String cFrOthOperateA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_inf_fr_operate_a
     *
     * @mbggenerated
     */
    private String cInfFrOperateA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_paid_goods_s
     *
     * @mbggenerated
     */
    private String cPaidGoodsS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_paid_to_for_empl
     *
     * @mbggenerated
     */
    private String cPaidToForEmpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_paid_for_taxes
     *
     * @mbggenerated
     */
    private String cPaidForTaxes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_clt_loan_adv
     *
     * @mbggenerated
     */
    private String nIncrCltLoanAdv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_dep_cbob
     *
     * @mbggenerated
     */
    private String nIncrDepCbob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_pay_claims_orig_inco
     *
     * @mbggenerated
     */
    private String cPayClaimsOrigInco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.pay_handling_chrg
     *
     * @mbggenerated
     */
    private String payHandlingChrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.pay_comm_insur_plcy
     *
     * @mbggenerated
     */
    private String payCommInsurPlcy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.oth_cash_pay_oper_act
     *
     * @mbggenerated
     */
    private String othCashPayOperAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.st_cash_out_act
     *
     * @mbggenerated
     */
    private String stCashOutAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_cashflow_act
     *
     * @mbggenerated
     */
    private String nCashflowAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.oth_recp_ral_inv_act
     *
     * @mbggenerated
     */
    private String othRecpRalInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_disp_withdrwl_invest
     *
     * @mbggenerated
     */
    private String cDispWithdrwlInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_recp_return_invest
     *
     * @mbggenerated
     */
    private String cRecpReturnInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_recp_disp_fiolta
     *
     * @mbggenerated
     */
    private String nRecpDispFiolta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_recp_disp_sobu
     *
     * @mbggenerated
     */
    private String nRecpDispSobu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.stot_inflows_inv_act
     *
     * @mbggenerated
     */
    private String stotInflowsInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_pay_acq_const_fiolta
     *
     * @mbggenerated
     */
    private String cPayAcqConstFiolta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_paid_invest
     *
     * @mbggenerated
     */
    private String cPaidInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_disp_subs_oth_biz
     *
     * @mbggenerated
     */
    private String nDispSubsOthBiz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.oth_pay_ral_inv_act
     *
     * @mbggenerated
     */
    private String othPayRalInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_pledge_loan
     *
     * @mbggenerated
     */
    private String nIncrPledgeLoan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.stot_out_inv_act
     *
     * @mbggenerated
     */
    private String stotOutInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_cashflow_inv_act
     *
     * @mbggenerated
     */
    private String nCashflowInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_recp_borrow
     *
     * @mbggenerated
     */
    private String cRecpBorrow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.proc_issue_bonds
     *
     * @mbggenerated
     */
    private String procIssueBonds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.oth_cash_recp_ral_fnc_act
     *
     * @mbggenerated
     */
    private String othCashRecpRalFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.stot_cash_in_fnc_act
     *
     * @mbggenerated
     */
    private String stotCashInFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.free_cashflow
     *
     * @mbggenerated
     */
    private String freeCashflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_prepay_amt_borr
     *
     * @mbggenerated
     */
    private String cPrepayAmtBorr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_pay_dist_dpcp_int_exp
     *
     * @mbggenerated
     */
    private String cPayDistDpcpIntExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.incl_dvd_profit_paid_sc_ms
     *
     * @mbggenerated
     */
    private String inclDvdProfitPaidScMs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.oth_cashpay_ral_fnc_act
     *
     * @mbggenerated
     */
    private String othCashpayRalFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.stot_cashout_fnc_act
     *
     * @mbggenerated
     */
    private String stotCashoutFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_cash_flows_fnc_act
     *
     * @mbggenerated
     */
    private String nCashFlowsFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.eff_fx_flu_cash
     *
     * @mbggenerated
     */
    private String effFxFluCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.n_incr_cash_cash_equ
     *
     * @mbggenerated
     */
    private String nIncrCashCashEqu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_cash_equ_beg_period
     *
     * @mbggenerated
     */
    private String cCashEquBegPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_cash_equ_end_period
     *
     * @mbggenerated
     */
    private String cCashEquEndPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.c_recp_cap_contrib
     *
     * @mbggenerated
     */
    private String cRecpCapContrib;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.incl_cash_rec_saims
     *
     * @mbggenerated
     */
    private String inclCashRecSaims;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.uncon_invest_loss
     *
     * @mbggenerated
     */
    private String unconInvestLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.prov_depr_assets
     *
     * @mbggenerated
     */
    private String provDeprAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.depr_fa_coga_dpba
     *
     * @mbggenerated
     */
    private String deprFaCogaDpba;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.amort_intang_assets
     *
     * @mbggenerated
     */
    private String amortIntangAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.lt_amort_deferred_exp
     *
     * @mbggenerated
     */
    private String ltAmortDeferredExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.decr_deferred_exp
     *
     * @mbggenerated
     */
    private String decrDeferredExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.incr_acc_exp
     *
     * @mbggenerated
     */
    private String incrAccExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.loss_disp_fiolta
     *
     * @mbggenerated
     */
    private String lossDispFiolta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.loss_scr_fa
     *
     * @mbggenerated
     */
    private String lossScrFa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.loss_fv_chg
     *
     * @mbggenerated
     */
    private String lossFvChg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.invest_loss
     *
     * @mbggenerated
     */
    private String investLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.decr_def_inc_tax_assets
     *
     * @mbggenerated
     */
    private String decrDefIncTaxAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.incr_def_inc_tax_liab
     *
     * @mbggenerated
     */
    private String incrDefIncTaxLiab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.decr_inventories
     *
     * @mbggenerated
     */
    private String decrInventories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.decr_oper_payable
     *
     * @mbggenerated
     */
    private String decrOperPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.incr_oper_payable
     *
     * @mbggenerated
     */
    private String incrOperPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.others
     *
     * @mbggenerated
     */
    private String others;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.im_net_cashflow_oper_act
     *
     * @mbggenerated
     */
    private String imNetCashflowOperAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.conv_debt_into_cap
     *
     * @mbggenerated
     */
    private String convDebtIntoCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.conv_copbonds_due_within_1y
     *
     * @mbggenerated
     */
    private String convCopbondsDueWithin1y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.fa_fnc_leases
     *
     * @mbggenerated
     */
    private String faFncLeases;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.end_bal_cash
     *
     * @mbggenerated
     */
    private String endBalCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.beg_bal_cash
     *
     * @mbggenerated
     */
    private String begBalCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.end_bal_cash_equ
     *
     * @mbggenerated
     */
    private String endBalCashEqu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.beg_bal_cash_equ
     *
     * @mbggenerated
     */
    private String begBalCashEqu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.im_n_incr_cash_equ
     *
     * @mbggenerated
     */
    private String imNIncrCashEqu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.update_flag
     *
     * @mbggenerated
     */
    private String updateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cash_flow.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.id
     *
     * @return the value of t_cash_flow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.id
     *
     * @param id the value for t_cash_flow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.ts_code
     *
     * @return the value of t_cash_flow.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.ts_code
     *
     * @param tsCode the value for t_cash_flow.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.ann_date
     *
     * @return the value of t_cash_flow.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.ann_date
     *
     * @param annDate the value for t_cash_flow.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.f_ann_date
     *
     * @return the value of t_cash_flow.f_ann_date
     *
     * @mbggenerated
     */
    public String getfAnnDate() {
        return fAnnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.f_ann_date
     *
     * @param fAnnDate the value for t_cash_flow.f_ann_date
     *
     * @mbggenerated
     */
    public void setfAnnDate(String fAnnDate) {
        this.fAnnDate = fAnnDate == null ? null : fAnnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.end_date
     *
     * @return the value of t_cash_flow.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.end_date
     *
     * @param endDate the value for t_cash_flow.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.comp_type
     *
     * @return the value of t_cash_flow.comp_type
     *
     * @mbggenerated
     */
    public String getCompType() {
        return compType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.comp_type
     *
     * @param compType the value for t_cash_flow.comp_type
     *
     * @mbggenerated
     */
    public void setCompType(String compType) {
        this.compType = compType == null ? null : compType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.report_type
     *
     * @return the value of t_cash_flow.report_type
     *
     * @mbggenerated
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.report_type
     *
     * @param reportType the value for t_cash_flow.report_type
     *
     * @mbggenerated
     */
    public void setReportType(String reportType) {
        this.reportType = reportType == null ? null : reportType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.net_profit
     *
     * @return the value of t_cash_flow.net_profit
     *
     * @mbggenerated
     */
    public String getNetProfit() {
        return netProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.net_profit
     *
     * @param netProfit the value for t_cash_flow.net_profit
     *
     * @mbggenerated
     */
    public void setNetProfit(String netProfit) {
        this.netProfit = netProfit == null ? null : netProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.finan_exp
     *
     * @return the value of t_cash_flow.finan_exp
     *
     * @mbggenerated
     */
    public String getFinanExp() {
        return finanExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.finan_exp
     *
     * @param finanExp the value for t_cash_flow.finan_exp
     *
     * @mbggenerated
     */
    public void setFinanExp(String finanExp) {
        this.finanExp = finanExp == null ? null : finanExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_fr_sale_sg
     *
     * @return the value of t_cash_flow.c_fr_sale_sg
     *
     * @mbggenerated
     */
    public String getcFrSaleSg() {
        return cFrSaleSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_fr_sale_sg
     *
     * @param cFrSaleSg the value for t_cash_flow.c_fr_sale_sg
     *
     * @mbggenerated
     */
    public void setcFrSaleSg(String cFrSaleSg) {
        this.cFrSaleSg = cFrSaleSg == null ? null : cFrSaleSg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.recp_tax_rends
     *
     * @return the value of t_cash_flow.recp_tax_rends
     *
     * @mbggenerated
     */
    public String getRecpTaxRends() {
        return recpTaxRends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.recp_tax_rends
     *
     * @param recpTaxRends the value for t_cash_flow.recp_tax_rends
     *
     * @mbggenerated
     */
    public void setRecpTaxRends(String recpTaxRends) {
        this.recpTaxRends = recpTaxRends == null ? null : recpTaxRends.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_depos_incr_fi
     *
     * @return the value of t_cash_flow.n_depos_incr_fi
     *
     * @mbggenerated
     */
    public String getnDeposIncrFi() {
        return nDeposIncrFi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_depos_incr_fi
     *
     * @param nDeposIncrFi the value for t_cash_flow.n_depos_incr_fi
     *
     * @mbggenerated
     */
    public void setnDeposIncrFi(String nDeposIncrFi) {
        this.nDeposIncrFi = nDeposIncrFi == null ? null : nDeposIncrFi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_loans_cb
     *
     * @return the value of t_cash_flow.n_incr_loans_cb
     *
     * @mbggenerated
     */
    public String getnIncrLoansCb() {
        return nIncrLoansCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_loans_cb
     *
     * @param nIncrLoansCb the value for t_cash_flow.n_incr_loans_cb
     *
     * @mbggenerated
     */
    public void setnIncrLoansCb(String nIncrLoansCb) {
        this.nIncrLoansCb = nIncrLoansCb == null ? null : nIncrLoansCb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_inc_borr_oth_fi
     *
     * @return the value of t_cash_flow.n_inc_borr_oth_fi
     *
     * @mbggenerated
     */
    public String getnIncBorrOthFi() {
        return nIncBorrOthFi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_inc_borr_oth_fi
     *
     * @param nIncBorrOthFi the value for t_cash_flow.n_inc_borr_oth_fi
     *
     * @mbggenerated
     */
    public void setnIncBorrOthFi(String nIncBorrOthFi) {
        this.nIncBorrOthFi = nIncBorrOthFi == null ? null : nIncBorrOthFi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.prem_fr_orig_contr
     *
     * @return the value of t_cash_flow.prem_fr_orig_contr
     *
     * @mbggenerated
     */
    public String getPremFrOrigContr() {
        return premFrOrigContr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.prem_fr_orig_contr
     *
     * @param premFrOrigContr the value for t_cash_flow.prem_fr_orig_contr
     *
     * @mbggenerated
     */
    public void setPremFrOrigContr(String premFrOrigContr) {
        this.premFrOrigContr = premFrOrigContr == null ? null : premFrOrigContr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_insured_dep
     *
     * @return the value of t_cash_flow.n_incr_insured_dep
     *
     * @mbggenerated
     */
    public String getnIncrInsuredDep() {
        return nIncrInsuredDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_insured_dep
     *
     * @param nIncrInsuredDep the value for t_cash_flow.n_incr_insured_dep
     *
     * @mbggenerated
     */
    public void setnIncrInsuredDep(String nIncrInsuredDep) {
        this.nIncrInsuredDep = nIncrInsuredDep == null ? null : nIncrInsuredDep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_reinsur_prem
     *
     * @return the value of t_cash_flow.n_reinsur_prem
     *
     * @mbggenerated
     */
    public String getnReinsurPrem() {
        return nReinsurPrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_reinsur_prem
     *
     * @param nReinsurPrem the value for t_cash_flow.n_reinsur_prem
     *
     * @mbggenerated
     */
    public void setnReinsurPrem(String nReinsurPrem) {
        this.nReinsurPrem = nReinsurPrem == null ? null : nReinsurPrem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_disp_tfa
     *
     * @return the value of t_cash_flow.n_incr_disp_tfa
     *
     * @mbggenerated
     */
    public String getnIncrDispTfa() {
        return nIncrDispTfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_disp_tfa
     *
     * @param nIncrDispTfa the value for t_cash_flow.n_incr_disp_tfa
     *
     * @mbggenerated
     */
    public void setnIncrDispTfa(String nIncrDispTfa) {
        this.nIncrDispTfa = nIncrDispTfa == null ? null : nIncrDispTfa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.ifc_cash_incr
     *
     * @return the value of t_cash_flow.ifc_cash_incr
     *
     * @mbggenerated
     */
    public String getIfcCashIncr() {
        return ifcCashIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.ifc_cash_incr
     *
     * @param ifcCashIncr the value for t_cash_flow.ifc_cash_incr
     *
     * @mbggenerated
     */
    public void setIfcCashIncr(String ifcCashIncr) {
        this.ifcCashIncr = ifcCashIncr == null ? null : ifcCashIncr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_disp_faas
     *
     * @return the value of t_cash_flow.n_incr_disp_faas
     *
     * @mbggenerated
     */
    public String getnIncrDispFaas() {
        return nIncrDispFaas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_disp_faas
     *
     * @param nIncrDispFaas the value for t_cash_flow.n_incr_disp_faas
     *
     * @mbggenerated
     */
    public void setnIncrDispFaas(String nIncrDispFaas) {
        this.nIncrDispFaas = nIncrDispFaas == null ? null : nIncrDispFaas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_loans_oth_bank
     *
     * @return the value of t_cash_flow.n_incr_loans_oth_bank
     *
     * @mbggenerated
     */
    public String getnIncrLoansOthBank() {
        return nIncrLoansOthBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_loans_oth_bank
     *
     * @param nIncrLoansOthBank the value for t_cash_flow.n_incr_loans_oth_bank
     *
     * @mbggenerated
     */
    public void setnIncrLoansOthBank(String nIncrLoansOthBank) {
        this.nIncrLoansOthBank = nIncrLoansOthBank == null ? null : nIncrLoansOthBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_cap_incr_repur
     *
     * @return the value of t_cash_flow.n_cap_incr_repur
     *
     * @mbggenerated
     */
    public String getnCapIncrRepur() {
        return nCapIncrRepur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_cap_incr_repur
     *
     * @param nCapIncrRepur the value for t_cash_flow.n_cap_incr_repur
     *
     * @mbggenerated
     */
    public void setnCapIncrRepur(String nCapIncrRepur) {
        this.nCapIncrRepur = nCapIncrRepur == null ? null : nCapIncrRepur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_fr_oth_operate_a
     *
     * @return the value of t_cash_flow.c_fr_oth_operate_a
     *
     * @mbggenerated
     */
    public String getcFrOthOperateA() {
        return cFrOthOperateA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_fr_oth_operate_a
     *
     * @param cFrOthOperateA the value for t_cash_flow.c_fr_oth_operate_a
     *
     * @mbggenerated
     */
    public void setcFrOthOperateA(String cFrOthOperateA) {
        this.cFrOthOperateA = cFrOthOperateA == null ? null : cFrOthOperateA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_inf_fr_operate_a
     *
     * @return the value of t_cash_flow.c_inf_fr_operate_a
     *
     * @mbggenerated
     */
    public String getcInfFrOperateA() {
        return cInfFrOperateA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_inf_fr_operate_a
     *
     * @param cInfFrOperateA the value for t_cash_flow.c_inf_fr_operate_a
     *
     * @mbggenerated
     */
    public void setcInfFrOperateA(String cInfFrOperateA) {
        this.cInfFrOperateA = cInfFrOperateA == null ? null : cInfFrOperateA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_paid_goods_s
     *
     * @return the value of t_cash_flow.c_paid_goods_s
     *
     * @mbggenerated
     */
    public String getcPaidGoodsS() {
        return cPaidGoodsS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_paid_goods_s
     *
     * @param cPaidGoodsS the value for t_cash_flow.c_paid_goods_s
     *
     * @mbggenerated
     */
    public void setcPaidGoodsS(String cPaidGoodsS) {
        this.cPaidGoodsS = cPaidGoodsS == null ? null : cPaidGoodsS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_paid_to_for_empl
     *
     * @return the value of t_cash_flow.c_paid_to_for_empl
     *
     * @mbggenerated
     */
    public String getcPaidToForEmpl() {
        return cPaidToForEmpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_paid_to_for_empl
     *
     * @param cPaidToForEmpl the value for t_cash_flow.c_paid_to_for_empl
     *
     * @mbggenerated
     */
    public void setcPaidToForEmpl(String cPaidToForEmpl) {
        this.cPaidToForEmpl = cPaidToForEmpl == null ? null : cPaidToForEmpl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_paid_for_taxes
     *
     * @return the value of t_cash_flow.c_paid_for_taxes
     *
     * @mbggenerated
     */
    public String getcPaidForTaxes() {
        return cPaidForTaxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_paid_for_taxes
     *
     * @param cPaidForTaxes the value for t_cash_flow.c_paid_for_taxes
     *
     * @mbggenerated
     */
    public void setcPaidForTaxes(String cPaidForTaxes) {
        this.cPaidForTaxes = cPaidForTaxes == null ? null : cPaidForTaxes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_clt_loan_adv
     *
     * @return the value of t_cash_flow.n_incr_clt_loan_adv
     *
     * @mbggenerated
     */
    public String getnIncrCltLoanAdv() {
        return nIncrCltLoanAdv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_clt_loan_adv
     *
     * @param nIncrCltLoanAdv the value for t_cash_flow.n_incr_clt_loan_adv
     *
     * @mbggenerated
     */
    public void setnIncrCltLoanAdv(String nIncrCltLoanAdv) {
        this.nIncrCltLoanAdv = nIncrCltLoanAdv == null ? null : nIncrCltLoanAdv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_dep_cbob
     *
     * @return the value of t_cash_flow.n_incr_dep_cbob
     *
     * @mbggenerated
     */
    public String getnIncrDepCbob() {
        return nIncrDepCbob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_dep_cbob
     *
     * @param nIncrDepCbob the value for t_cash_flow.n_incr_dep_cbob
     *
     * @mbggenerated
     */
    public void setnIncrDepCbob(String nIncrDepCbob) {
        this.nIncrDepCbob = nIncrDepCbob == null ? null : nIncrDepCbob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_pay_claims_orig_inco
     *
     * @return the value of t_cash_flow.c_pay_claims_orig_inco
     *
     * @mbggenerated
     */
    public String getcPayClaimsOrigInco() {
        return cPayClaimsOrigInco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_pay_claims_orig_inco
     *
     * @param cPayClaimsOrigInco the value for t_cash_flow.c_pay_claims_orig_inco
     *
     * @mbggenerated
     */
    public void setcPayClaimsOrigInco(String cPayClaimsOrigInco) {
        this.cPayClaimsOrigInco = cPayClaimsOrigInco == null ? null : cPayClaimsOrigInco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.pay_handling_chrg
     *
     * @return the value of t_cash_flow.pay_handling_chrg
     *
     * @mbggenerated
     */
    public String getPayHandlingChrg() {
        return payHandlingChrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.pay_handling_chrg
     *
     * @param payHandlingChrg the value for t_cash_flow.pay_handling_chrg
     *
     * @mbggenerated
     */
    public void setPayHandlingChrg(String payHandlingChrg) {
        this.payHandlingChrg = payHandlingChrg == null ? null : payHandlingChrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.pay_comm_insur_plcy
     *
     * @return the value of t_cash_flow.pay_comm_insur_plcy
     *
     * @mbggenerated
     */
    public String getPayCommInsurPlcy() {
        return payCommInsurPlcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.pay_comm_insur_plcy
     *
     * @param payCommInsurPlcy the value for t_cash_flow.pay_comm_insur_plcy
     *
     * @mbggenerated
     */
    public void setPayCommInsurPlcy(String payCommInsurPlcy) {
        this.payCommInsurPlcy = payCommInsurPlcy == null ? null : payCommInsurPlcy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.oth_cash_pay_oper_act
     *
     * @return the value of t_cash_flow.oth_cash_pay_oper_act
     *
     * @mbggenerated
     */
    public String getOthCashPayOperAct() {
        return othCashPayOperAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.oth_cash_pay_oper_act
     *
     * @param othCashPayOperAct the value for t_cash_flow.oth_cash_pay_oper_act
     *
     * @mbggenerated
     */
    public void setOthCashPayOperAct(String othCashPayOperAct) {
        this.othCashPayOperAct = othCashPayOperAct == null ? null : othCashPayOperAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.st_cash_out_act
     *
     * @return the value of t_cash_flow.st_cash_out_act
     *
     * @mbggenerated
     */
    public String getStCashOutAct() {
        return stCashOutAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.st_cash_out_act
     *
     * @param stCashOutAct the value for t_cash_flow.st_cash_out_act
     *
     * @mbggenerated
     */
    public void setStCashOutAct(String stCashOutAct) {
        this.stCashOutAct = stCashOutAct == null ? null : stCashOutAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_cashflow_act
     *
     * @return the value of t_cash_flow.n_cashflow_act
     *
     * @mbggenerated
     */
    public String getnCashflowAct() {
        return nCashflowAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_cashflow_act
     *
     * @param nCashflowAct the value for t_cash_flow.n_cashflow_act
     *
     * @mbggenerated
     */
    public void setnCashflowAct(String nCashflowAct) {
        this.nCashflowAct = nCashflowAct == null ? null : nCashflowAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.oth_recp_ral_inv_act
     *
     * @return the value of t_cash_flow.oth_recp_ral_inv_act
     *
     * @mbggenerated
     */
    public String getOthRecpRalInvAct() {
        return othRecpRalInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.oth_recp_ral_inv_act
     *
     * @param othRecpRalInvAct the value for t_cash_flow.oth_recp_ral_inv_act
     *
     * @mbggenerated
     */
    public void setOthRecpRalInvAct(String othRecpRalInvAct) {
        this.othRecpRalInvAct = othRecpRalInvAct == null ? null : othRecpRalInvAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_disp_withdrwl_invest
     *
     * @return the value of t_cash_flow.c_disp_withdrwl_invest
     *
     * @mbggenerated
     */
    public String getcDispWithdrwlInvest() {
        return cDispWithdrwlInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_disp_withdrwl_invest
     *
     * @param cDispWithdrwlInvest the value for t_cash_flow.c_disp_withdrwl_invest
     *
     * @mbggenerated
     */
    public void setcDispWithdrwlInvest(String cDispWithdrwlInvest) {
        this.cDispWithdrwlInvest = cDispWithdrwlInvest == null ? null : cDispWithdrwlInvest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_recp_return_invest
     *
     * @return the value of t_cash_flow.c_recp_return_invest
     *
     * @mbggenerated
     */
    public String getcRecpReturnInvest() {
        return cRecpReturnInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_recp_return_invest
     *
     * @param cRecpReturnInvest the value for t_cash_flow.c_recp_return_invest
     *
     * @mbggenerated
     */
    public void setcRecpReturnInvest(String cRecpReturnInvest) {
        this.cRecpReturnInvest = cRecpReturnInvest == null ? null : cRecpReturnInvest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_recp_disp_fiolta
     *
     * @return the value of t_cash_flow.n_recp_disp_fiolta
     *
     * @mbggenerated
     */
    public String getnRecpDispFiolta() {
        return nRecpDispFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_recp_disp_fiolta
     *
     * @param nRecpDispFiolta the value for t_cash_flow.n_recp_disp_fiolta
     *
     * @mbggenerated
     */
    public void setnRecpDispFiolta(String nRecpDispFiolta) {
        this.nRecpDispFiolta = nRecpDispFiolta == null ? null : nRecpDispFiolta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_recp_disp_sobu
     *
     * @return the value of t_cash_flow.n_recp_disp_sobu
     *
     * @mbggenerated
     */
    public String getnRecpDispSobu() {
        return nRecpDispSobu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_recp_disp_sobu
     *
     * @param nRecpDispSobu the value for t_cash_flow.n_recp_disp_sobu
     *
     * @mbggenerated
     */
    public void setnRecpDispSobu(String nRecpDispSobu) {
        this.nRecpDispSobu = nRecpDispSobu == null ? null : nRecpDispSobu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.stot_inflows_inv_act
     *
     * @return the value of t_cash_flow.stot_inflows_inv_act
     *
     * @mbggenerated
     */
    public String getStotInflowsInvAct() {
        return stotInflowsInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.stot_inflows_inv_act
     *
     * @param stotInflowsInvAct the value for t_cash_flow.stot_inflows_inv_act
     *
     * @mbggenerated
     */
    public void setStotInflowsInvAct(String stotInflowsInvAct) {
        this.stotInflowsInvAct = stotInflowsInvAct == null ? null : stotInflowsInvAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_pay_acq_const_fiolta
     *
     * @return the value of t_cash_flow.c_pay_acq_const_fiolta
     *
     * @mbggenerated
     */
    public String getcPayAcqConstFiolta() {
        return cPayAcqConstFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_pay_acq_const_fiolta
     *
     * @param cPayAcqConstFiolta the value for t_cash_flow.c_pay_acq_const_fiolta
     *
     * @mbggenerated
     */
    public void setcPayAcqConstFiolta(String cPayAcqConstFiolta) {
        this.cPayAcqConstFiolta = cPayAcqConstFiolta == null ? null : cPayAcqConstFiolta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_paid_invest
     *
     * @return the value of t_cash_flow.c_paid_invest
     *
     * @mbggenerated
     */
    public String getcPaidInvest() {
        return cPaidInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_paid_invest
     *
     * @param cPaidInvest the value for t_cash_flow.c_paid_invest
     *
     * @mbggenerated
     */
    public void setcPaidInvest(String cPaidInvest) {
        this.cPaidInvest = cPaidInvest == null ? null : cPaidInvest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_disp_subs_oth_biz
     *
     * @return the value of t_cash_flow.n_disp_subs_oth_biz
     *
     * @mbggenerated
     */
    public String getnDispSubsOthBiz() {
        return nDispSubsOthBiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_disp_subs_oth_biz
     *
     * @param nDispSubsOthBiz the value for t_cash_flow.n_disp_subs_oth_biz
     *
     * @mbggenerated
     */
    public void setnDispSubsOthBiz(String nDispSubsOthBiz) {
        this.nDispSubsOthBiz = nDispSubsOthBiz == null ? null : nDispSubsOthBiz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.oth_pay_ral_inv_act
     *
     * @return the value of t_cash_flow.oth_pay_ral_inv_act
     *
     * @mbggenerated
     */
    public String getOthPayRalInvAct() {
        return othPayRalInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.oth_pay_ral_inv_act
     *
     * @param othPayRalInvAct the value for t_cash_flow.oth_pay_ral_inv_act
     *
     * @mbggenerated
     */
    public void setOthPayRalInvAct(String othPayRalInvAct) {
        this.othPayRalInvAct = othPayRalInvAct == null ? null : othPayRalInvAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_pledge_loan
     *
     * @return the value of t_cash_flow.n_incr_pledge_loan
     *
     * @mbggenerated
     */
    public String getnIncrPledgeLoan() {
        return nIncrPledgeLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_pledge_loan
     *
     * @param nIncrPledgeLoan the value for t_cash_flow.n_incr_pledge_loan
     *
     * @mbggenerated
     */
    public void setnIncrPledgeLoan(String nIncrPledgeLoan) {
        this.nIncrPledgeLoan = nIncrPledgeLoan == null ? null : nIncrPledgeLoan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.stot_out_inv_act
     *
     * @return the value of t_cash_flow.stot_out_inv_act
     *
     * @mbggenerated
     */
    public String getStotOutInvAct() {
        return stotOutInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.stot_out_inv_act
     *
     * @param stotOutInvAct the value for t_cash_flow.stot_out_inv_act
     *
     * @mbggenerated
     */
    public void setStotOutInvAct(String stotOutInvAct) {
        this.stotOutInvAct = stotOutInvAct == null ? null : stotOutInvAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_cashflow_inv_act
     *
     * @return the value of t_cash_flow.n_cashflow_inv_act
     *
     * @mbggenerated
     */
    public String getnCashflowInvAct() {
        return nCashflowInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_cashflow_inv_act
     *
     * @param nCashflowInvAct the value for t_cash_flow.n_cashflow_inv_act
     *
     * @mbggenerated
     */
    public void setnCashflowInvAct(String nCashflowInvAct) {
        this.nCashflowInvAct = nCashflowInvAct == null ? null : nCashflowInvAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_recp_borrow
     *
     * @return the value of t_cash_flow.c_recp_borrow
     *
     * @mbggenerated
     */
    public String getcRecpBorrow() {
        return cRecpBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_recp_borrow
     *
     * @param cRecpBorrow the value for t_cash_flow.c_recp_borrow
     *
     * @mbggenerated
     */
    public void setcRecpBorrow(String cRecpBorrow) {
        this.cRecpBorrow = cRecpBorrow == null ? null : cRecpBorrow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.proc_issue_bonds
     *
     * @return the value of t_cash_flow.proc_issue_bonds
     *
     * @mbggenerated
     */
    public String getProcIssueBonds() {
        return procIssueBonds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.proc_issue_bonds
     *
     * @param procIssueBonds the value for t_cash_flow.proc_issue_bonds
     *
     * @mbggenerated
     */
    public void setProcIssueBonds(String procIssueBonds) {
        this.procIssueBonds = procIssueBonds == null ? null : procIssueBonds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.oth_cash_recp_ral_fnc_act
     *
     * @return the value of t_cash_flow.oth_cash_recp_ral_fnc_act
     *
     * @mbggenerated
     */
    public String getOthCashRecpRalFncAct() {
        return othCashRecpRalFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.oth_cash_recp_ral_fnc_act
     *
     * @param othCashRecpRalFncAct the value for t_cash_flow.oth_cash_recp_ral_fnc_act
     *
     * @mbggenerated
     */
    public void setOthCashRecpRalFncAct(String othCashRecpRalFncAct) {
        this.othCashRecpRalFncAct = othCashRecpRalFncAct == null ? null : othCashRecpRalFncAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.stot_cash_in_fnc_act
     *
     * @return the value of t_cash_flow.stot_cash_in_fnc_act
     *
     * @mbggenerated
     */
    public String getStotCashInFncAct() {
        return stotCashInFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.stot_cash_in_fnc_act
     *
     * @param stotCashInFncAct the value for t_cash_flow.stot_cash_in_fnc_act
     *
     * @mbggenerated
     */
    public void setStotCashInFncAct(String stotCashInFncAct) {
        this.stotCashInFncAct = stotCashInFncAct == null ? null : stotCashInFncAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.free_cashflow
     *
     * @return the value of t_cash_flow.free_cashflow
     *
     * @mbggenerated
     */
    public String getFreeCashflow() {
        return freeCashflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.free_cashflow
     *
     * @param freeCashflow the value for t_cash_flow.free_cashflow
     *
     * @mbggenerated
     */
    public void setFreeCashflow(String freeCashflow) {
        this.freeCashflow = freeCashflow == null ? null : freeCashflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_prepay_amt_borr
     *
     * @return the value of t_cash_flow.c_prepay_amt_borr
     *
     * @mbggenerated
     */
    public String getcPrepayAmtBorr() {
        return cPrepayAmtBorr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_prepay_amt_borr
     *
     * @param cPrepayAmtBorr the value for t_cash_flow.c_prepay_amt_borr
     *
     * @mbggenerated
     */
    public void setcPrepayAmtBorr(String cPrepayAmtBorr) {
        this.cPrepayAmtBorr = cPrepayAmtBorr == null ? null : cPrepayAmtBorr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_pay_dist_dpcp_int_exp
     *
     * @return the value of t_cash_flow.c_pay_dist_dpcp_int_exp
     *
     * @mbggenerated
     */
    public String getcPayDistDpcpIntExp() {
        return cPayDistDpcpIntExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_pay_dist_dpcp_int_exp
     *
     * @param cPayDistDpcpIntExp the value for t_cash_flow.c_pay_dist_dpcp_int_exp
     *
     * @mbggenerated
     */
    public void setcPayDistDpcpIntExp(String cPayDistDpcpIntExp) {
        this.cPayDistDpcpIntExp = cPayDistDpcpIntExp == null ? null : cPayDistDpcpIntExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.incl_dvd_profit_paid_sc_ms
     *
     * @return the value of t_cash_flow.incl_dvd_profit_paid_sc_ms
     *
     * @mbggenerated
     */
    public String getInclDvdProfitPaidScMs() {
        return inclDvdProfitPaidScMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.incl_dvd_profit_paid_sc_ms
     *
     * @param inclDvdProfitPaidScMs the value for t_cash_flow.incl_dvd_profit_paid_sc_ms
     *
     * @mbggenerated
     */
    public void setInclDvdProfitPaidScMs(String inclDvdProfitPaidScMs) {
        this.inclDvdProfitPaidScMs = inclDvdProfitPaidScMs == null ? null : inclDvdProfitPaidScMs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.oth_cashpay_ral_fnc_act
     *
     * @return the value of t_cash_flow.oth_cashpay_ral_fnc_act
     *
     * @mbggenerated
     */
    public String getOthCashpayRalFncAct() {
        return othCashpayRalFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.oth_cashpay_ral_fnc_act
     *
     * @param othCashpayRalFncAct the value for t_cash_flow.oth_cashpay_ral_fnc_act
     *
     * @mbggenerated
     */
    public void setOthCashpayRalFncAct(String othCashpayRalFncAct) {
        this.othCashpayRalFncAct = othCashpayRalFncAct == null ? null : othCashpayRalFncAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.stot_cashout_fnc_act
     *
     * @return the value of t_cash_flow.stot_cashout_fnc_act
     *
     * @mbggenerated
     */
    public String getStotCashoutFncAct() {
        return stotCashoutFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.stot_cashout_fnc_act
     *
     * @param stotCashoutFncAct the value for t_cash_flow.stot_cashout_fnc_act
     *
     * @mbggenerated
     */
    public void setStotCashoutFncAct(String stotCashoutFncAct) {
        this.stotCashoutFncAct = stotCashoutFncAct == null ? null : stotCashoutFncAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_cash_flows_fnc_act
     *
     * @return the value of t_cash_flow.n_cash_flows_fnc_act
     *
     * @mbggenerated
     */
    public String getnCashFlowsFncAct() {
        return nCashFlowsFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_cash_flows_fnc_act
     *
     * @param nCashFlowsFncAct the value for t_cash_flow.n_cash_flows_fnc_act
     *
     * @mbggenerated
     */
    public void setnCashFlowsFncAct(String nCashFlowsFncAct) {
        this.nCashFlowsFncAct = nCashFlowsFncAct == null ? null : nCashFlowsFncAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.eff_fx_flu_cash
     *
     * @return the value of t_cash_flow.eff_fx_flu_cash
     *
     * @mbggenerated
     */
    public String getEffFxFluCash() {
        return effFxFluCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.eff_fx_flu_cash
     *
     * @param effFxFluCash the value for t_cash_flow.eff_fx_flu_cash
     *
     * @mbggenerated
     */
    public void setEffFxFluCash(String effFxFluCash) {
        this.effFxFluCash = effFxFluCash == null ? null : effFxFluCash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.n_incr_cash_cash_equ
     *
     * @return the value of t_cash_flow.n_incr_cash_cash_equ
     *
     * @mbggenerated
     */
    public String getnIncrCashCashEqu() {
        return nIncrCashCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.n_incr_cash_cash_equ
     *
     * @param nIncrCashCashEqu the value for t_cash_flow.n_incr_cash_cash_equ
     *
     * @mbggenerated
     */
    public void setnIncrCashCashEqu(String nIncrCashCashEqu) {
        this.nIncrCashCashEqu = nIncrCashCashEqu == null ? null : nIncrCashCashEqu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_cash_equ_beg_period
     *
     * @return the value of t_cash_flow.c_cash_equ_beg_period
     *
     * @mbggenerated
     */
    public String getcCashEquBegPeriod() {
        return cCashEquBegPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_cash_equ_beg_period
     *
     * @param cCashEquBegPeriod the value for t_cash_flow.c_cash_equ_beg_period
     *
     * @mbggenerated
     */
    public void setcCashEquBegPeriod(String cCashEquBegPeriod) {
        this.cCashEquBegPeriod = cCashEquBegPeriod == null ? null : cCashEquBegPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_cash_equ_end_period
     *
     * @return the value of t_cash_flow.c_cash_equ_end_period
     *
     * @mbggenerated
     */
    public String getcCashEquEndPeriod() {
        return cCashEquEndPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_cash_equ_end_period
     *
     * @param cCashEquEndPeriod the value for t_cash_flow.c_cash_equ_end_period
     *
     * @mbggenerated
     */
    public void setcCashEquEndPeriod(String cCashEquEndPeriod) {
        this.cCashEquEndPeriod = cCashEquEndPeriod == null ? null : cCashEquEndPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.c_recp_cap_contrib
     *
     * @return the value of t_cash_flow.c_recp_cap_contrib
     *
     * @mbggenerated
     */
    public String getcRecpCapContrib() {
        return cRecpCapContrib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.c_recp_cap_contrib
     *
     * @param cRecpCapContrib the value for t_cash_flow.c_recp_cap_contrib
     *
     * @mbggenerated
     */
    public void setcRecpCapContrib(String cRecpCapContrib) {
        this.cRecpCapContrib = cRecpCapContrib == null ? null : cRecpCapContrib.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.incl_cash_rec_saims
     *
     * @return the value of t_cash_flow.incl_cash_rec_saims
     *
     * @mbggenerated
     */
    public String getInclCashRecSaims() {
        return inclCashRecSaims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.incl_cash_rec_saims
     *
     * @param inclCashRecSaims the value for t_cash_flow.incl_cash_rec_saims
     *
     * @mbggenerated
     */
    public void setInclCashRecSaims(String inclCashRecSaims) {
        this.inclCashRecSaims = inclCashRecSaims == null ? null : inclCashRecSaims.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.uncon_invest_loss
     *
     * @return the value of t_cash_flow.uncon_invest_loss
     *
     * @mbggenerated
     */
    public String getUnconInvestLoss() {
        return unconInvestLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.uncon_invest_loss
     *
     * @param unconInvestLoss the value for t_cash_flow.uncon_invest_loss
     *
     * @mbggenerated
     */
    public void setUnconInvestLoss(String unconInvestLoss) {
        this.unconInvestLoss = unconInvestLoss == null ? null : unconInvestLoss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.prov_depr_assets
     *
     * @return the value of t_cash_flow.prov_depr_assets
     *
     * @mbggenerated
     */
    public String getProvDeprAssets() {
        return provDeprAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.prov_depr_assets
     *
     * @param provDeprAssets the value for t_cash_flow.prov_depr_assets
     *
     * @mbggenerated
     */
    public void setProvDeprAssets(String provDeprAssets) {
        this.provDeprAssets = provDeprAssets == null ? null : provDeprAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.depr_fa_coga_dpba
     *
     * @return the value of t_cash_flow.depr_fa_coga_dpba
     *
     * @mbggenerated
     */
    public String getDeprFaCogaDpba() {
        return deprFaCogaDpba;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.depr_fa_coga_dpba
     *
     * @param deprFaCogaDpba the value for t_cash_flow.depr_fa_coga_dpba
     *
     * @mbggenerated
     */
    public void setDeprFaCogaDpba(String deprFaCogaDpba) {
        this.deprFaCogaDpba = deprFaCogaDpba == null ? null : deprFaCogaDpba.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.amort_intang_assets
     *
     * @return the value of t_cash_flow.amort_intang_assets
     *
     * @mbggenerated
     */
    public String getAmortIntangAssets() {
        return amortIntangAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.amort_intang_assets
     *
     * @param amortIntangAssets the value for t_cash_flow.amort_intang_assets
     *
     * @mbggenerated
     */
    public void setAmortIntangAssets(String amortIntangAssets) {
        this.amortIntangAssets = amortIntangAssets == null ? null : amortIntangAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.lt_amort_deferred_exp
     *
     * @return the value of t_cash_flow.lt_amort_deferred_exp
     *
     * @mbggenerated
     */
    public String getLtAmortDeferredExp() {
        return ltAmortDeferredExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.lt_amort_deferred_exp
     *
     * @param ltAmortDeferredExp the value for t_cash_flow.lt_amort_deferred_exp
     *
     * @mbggenerated
     */
    public void setLtAmortDeferredExp(String ltAmortDeferredExp) {
        this.ltAmortDeferredExp = ltAmortDeferredExp == null ? null : ltAmortDeferredExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.decr_deferred_exp
     *
     * @return the value of t_cash_flow.decr_deferred_exp
     *
     * @mbggenerated
     */
    public String getDecrDeferredExp() {
        return decrDeferredExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.decr_deferred_exp
     *
     * @param decrDeferredExp the value for t_cash_flow.decr_deferred_exp
     *
     * @mbggenerated
     */
    public void setDecrDeferredExp(String decrDeferredExp) {
        this.decrDeferredExp = decrDeferredExp == null ? null : decrDeferredExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.incr_acc_exp
     *
     * @return the value of t_cash_flow.incr_acc_exp
     *
     * @mbggenerated
     */
    public String getIncrAccExp() {
        return incrAccExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.incr_acc_exp
     *
     * @param incrAccExp the value for t_cash_flow.incr_acc_exp
     *
     * @mbggenerated
     */
    public void setIncrAccExp(String incrAccExp) {
        this.incrAccExp = incrAccExp == null ? null : incrAccExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.loss_disp_fiolta
     *
     * @return the value of t_cash_flow.loss_disp_fiolta
     *
     * @mbggenerated
     */
    public String getLossDispFiolta() {
        return lossDispFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.loss_disp_fiolta
     *
     * @param lossDispFiolta the value for t_cash_flow.loss_disp_fiolta
     *
     * @mbggenerated
     */
    public void setLossDispFiolta(String lossDispFiolta) {
        this.lossDispFiolta = lossDispFiolta == null ? null : lossDispFiolta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.loss_scr_fa
     *
     * @return the value of t_cash_flow.loss_scr_fa
     *
     * @mbggenerated
     */
    public String getLossScrFa() {
        return lossScrFa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.loss_scr_fa
     *
     * @param lossScrFa the value for t_cash_flow.loss_scr_fa
     *
     * @mbggenerated
     */
    public void setLossScrFa(String lossScrFa) {
        this.lossScrFa = lossScrFa == null ? null : lossScrFa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.loss_fv_chg
     *
     * @return the value of t_cash_flow.loss_fv_chg
     *
     * @mbggenerated
     */
    public String getLossFvChg() {
        return lossFvChg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.loss_fv_chg
     *
     * @param lossFvChg the value for t_cash_flow.loss_fv_chg
     *
     * @mbggenerated
     */
    public void setLossFvChg(String lossFvChg) {
        this.lossFvChg = lossFvChg == null ? null : lossFvChg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.invest_loss
     *
     * @return the value of t_cash_flow.invest_loss
     *
     * @mbggenerated
     */
    public String getInvestLoss() {
        return investLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.invest_loss
     *
     * @param investLoss the value for t_cash_flow.invest_loss
     *
     * @mbggenerated
     */
    public void setInvestLoss(String investLoss) {
        this.investLoss = investLoss == null ? null : investLoss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.decr_def_inc_tax_assets
     *
     * @return the value of t_cash_flow.decr_def_inc_tax_assets
     *
     * @mbggenerated
     */
    public String getDecrDefIncTaxAssets() {
        return decrDefIncTaxAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.decr_def_inc_tax_assets
     *
     * @param decrDefIncTaxAssets the value for t_cash_flow.decr_def_inc_tax_assets
     *
     * @mbggenerated
     */
    public void setDecrDefIncTaxAssets(String decrDefIncTaxAssets) {
        this.decrDefIncTaxAssets = decrDefIncTaxAssets == null ? null : decrDefIncTaxAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.incr_def_inc_tax_liab
     *
     * @return the value of t_cash_flow.incr_def_inc_tax_liab
     *
     * @mbggenerated
     */
    public String getIncrDefIncTaxLiab() {
        return incrDefIncTaxLiab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.incr_def_inc_tax_liab
     *
     * @param incrDefIncTaxLiab the value for t_cash_flow.incr_def_inc_tax_liab
     *
     * @mbggenerated
     */
    public void setIncrDefIncTaxLiab(String incrDefIncTaxLiab) {
        this.incrDefIncTaxLiab = incrDefIncTaxLiab == null ? null : incrDefIncTaxLiab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.decr_inventories
     *
     * @return the value of t_cash_flow.decr_inventories
     *
     * @mbggenerated
     */
    public String getDecrInventories() {
        return decrInventories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.decr_inventories
     *
     * @param decrInventories the value for t_cash_flow.decr_inventories
     *
     * @mbggenerated
     */
    public void setDecrInventories(String decrInventories) {
        this.decrInventories = decrInventories == null ? null : decrInventories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.decr_oper_payable
     *
     * @return the value of t_cash_flow.decr_oper_payable
     *
     * @mbggenerated
     */
    public String getDecrOperPayable() {
        return decrOperPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.decr_oper_payable
     *
     * @param decrOperPayable the value for t_cash_flow.decr_oper_payable
     *
     * @mbggenerated
     */
    public void setDecrOperPayable(String decrOperPayable) {
        this.decrOperPayable = decrOperPayable == null ? null : decrOperPayable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.incr_oper_payable
     *
     * @return the value of t_cash_flow.incr_oper_payable
     *
     * @mbggenerated
     */
    public String getIncrOperPayable() {
        return incrOperPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.incr_oper_payable
     *
     * @param incrOperPayable the value for t_cash_flow.incr_oper_payable
     *
     * @mbggenerated
     */
    public void setIncrOperPayable(String incrOperPayable) {
        this.incrOperPayable = incrOperPayable == null ? null : incrOperPayable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.others
     *
     * @return the value of t_cash_flow.others
     *
     * @mbggenerated
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.others
     *
     * @param others the value for t_cash_flow.others
     *
     * @mbggenerated
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.im_net_cashflow_oper_act
     *
     * @return the value of t_cash_flow.im_net_cashflow_oper_act
     *
     * @mbggenerated
     */
    public String getImNetCashflowOperAct() {
        return imNetCashflowOperAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.im_net_cashflow_oper_act
     *
     * @param imNetCashflowOperAct the value for t_cash_flow.im_net_cashflow_oper_act
     *
     * @mbggenerated
     */
    public void setImNetCashflowOperAct(String imNetCashflowOperAct) {
        this.imNetCashflowOperAct = imNetCashflowOperAct == null ? null : imNetCashflowOperAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.conv_debt_into_cap
     *
     * @return the value of t_cash_flow.conv_debt_into_cap
     *
     * @mbggenerated
     */
    public String getConvDebtIntoCap() {
        return convDebtIntoCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.conv_debt_into_cap
     *
     * @param convDebtIntoCap the value for t_cash_flow.conv_debt_into_cap
     *
     * @mbggenerated
     */
    public void setConvDebtIntoCap(String convDebtIntoCap) {
        this.convDebtIntoCap = convDebtIntoCap == null ? null : convDebtIntoCap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.conv_copbonds_due_within_1y
     *
     * @return the value of t_cash_flow.conv_copbonds_due_within_1y
     *
     * @mbggenerated
     */
    public String getConvCopbondsDueWithin1y() {
        return convCopbondsDueWithin1y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.conv_copbonds_due_within_1y
     *
     * @param convCopbondsDueWithin1y the value for t_cash_flow.conv_copbonds_due_within_1y
     *
     * @mbggenerated
     */
    public void setConvCopbondsDueWithin1y(String convCopbondsDueWithin1y) {
        this.convCopbondsDueWithin1y = convCopbondsDueWithin1y == null ? null : convCopbondsDueWithin1y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.fa_fnc_leases
     *
     * @return the value of t_cash_flow.fa_fnc_leases
     *
     * @mbggenerated
     */
    public String getFaFncLeases() {
        return faFncLeases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.fa_fnc_leases
     *
     * @param faFncLeases the value for t_cash_flow.fa_fnc_leases
     *
     * @mbggenerated
     */
    public void setFaFncLeases(String faFncLeases) {
        this.faFncLeases = faFncLeases == null ? null : faFncLeases.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.end_bal_cash
     *
     * @return the value of t_cash_flow.end_bal_cash
     *
     * @mbggenerated
     */
    public String getEndBalCash() {
        return endBalCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.end_bal_cash
     *
     * @param endBalCash the value for t_cash_flow.end_bal_cash
     *
     * @mbggenerated
     */
    public void setEndBalCash(String endBalCash) {
        this.endBalCash = endBalCash == null ? null : endBalCash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.beg_bal_cash
     *
     * @return the value of t_cash_flow.beg_bal_cash
     *
     * @mbggenerated
     */
    public String getBegBalCash() {
        return begBalCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.beg_bal_cash
     *
     * @param begBalCash the value for t_cash_flow.beg_bal_cash
     *
     * @mbggenerated
     */
    public void setBegBalCash(String begBalCash) {
        this.begBalCash = begBalCash == null ? null : begBalCash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.end_bal_cash_equ
     *
     * @return the value of t_cash_flow.end_bal_cash_equ
     *
     * @mbggenerated
     */
    public String getEndBalCashEqu() {
        return endBalCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.end_bal_cash_equ
     *
     * @param endBalCashEqu the value for t_cash_flow.end_bal_cash_equ
     *
     * @mbggenerated
     */
    public void setEndBalCashEqu(String endBalCashEqu) {
        this.endBalCashEqu = endBalCashEqu == null ? null : endBalCashEqu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.beg_bal_cash_equ
     *
     * @return the value of t_cash_flow.beg_bal_cash_equ
     *
     * @mbggenerated
     */
    public String getBegBalCashEqu() {
        return begBalCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.beg_bal_cash_equ
     *
     * @param begBalCashEqu the value for t_cash_flow.beg_bal_cash_equ
     *
     * @mbggenerated
     */
    public void setBegBalCashEqu(String begBalCashEqu) {
        this.begBalCashEqu = begBalCashEqu == null ? null : begBalCashEqu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.im_n_incr_cash_equ
     *
     * @return the value of t_cash_flow.im_n_incr_cash_equ
     *
     * @mbggenerated
     */
    public String getImNIncrCashEqu() {
        return imNIncrCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.im_n_incr_cash_equ
     *
     * @param imNIncrCashEqu the value for t_cash_flow.im_n_incr_cash_equ
     *
     * @mbggenerated
     */
    public void setImNIncrCashEqu(String imNIncrCashEqu) {
        this.imNIncrCashEqu = imNIncrCashEqu == null ? null : imNIncrCashEqu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.update_flag
     *
     * @return the value of t_cash_flow.update_flag
     *
     * @mbggenerated
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.update_flag
     *
     * @param updateFlag the value for t_cash_flow.update_flag
     *
     * @mbggenerated
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag == null ? null : updateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.create_time
     *
     * @return the value of t_cash_flow.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.create_time
     *
     * @param createTime the value for t_cash_flow.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cash_flow.update_time
     *
     * @return the value of t_cash_flow.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cash_flow.update_time
     *
     * @param updateTime the value for t_cash_flow.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}