package com.yskj.push.domain;

import java.util.Date;

public class DisclosureDate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.pre_date
     *
     * @mbggenerated
     */
    private String preDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.actual_date
     *
     * @mbggenerated
     */
    private String actualDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.modify_date
     *
     * @mbggenerated
     */
    private String modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_disclosure_date.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.id
     *
     * @return the value of t_disclosure_date.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.id
     *
     * @param id the value for t_disclosure_date.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.ts_code
     *
     * @return the value of t_disclosure_date.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.ts_code
     *
     * @param tsCode the value for t_disclosure_date.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.ann_date
     *
     * @return the value of t_disclosure_date.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.ann_date
     *
     * @param annDate the value for t_disclosure_date.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.end_date
     *
     * @return the value of t_disclosure_date.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.end_date
     *
     * @param endDate the value for t_disclosure_date.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.pre_date
     *
     * @return the value of t_disclosure_date.pre_date
     *
     * @mbggenerated
     */
    public String getPreDate() {
        return preDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.pre_date
     *
     * @param preDate the value for t_disclosure_date.pre_date
     *
     * @mbggenerated
     */
    public void setPreDate(String preDate) {
        this.preDate = preDate == null ? null : preDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.actual_date
     *
     * @return the value of t_disclosure_date.actual_date
     *
     * @mbggenerated
     */
    public String getActualDate() {
        return actualDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.actual_date
     *
     * @param actualDate the value for t_disclosure_date.actual_date
     *
     * @mbggenerated
     */
    public void setActualDate(String actualDate) {
        this.actualDate = actualDate == null ? null : actualDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.modify_date
     *
     * @return the value of t_disclosure_date.modify_date
     *
     * @mbggenerated
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.modify_date
     *
     * @param modifyDate the value for t_disclosure_date.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate == null ? null : modifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.create_time
     *
     * @return the value of t_disclosure_date.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.create_time
     *
     * @param createTime the value for t_disclosure_date.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_disclosure_date.update_time
     *
     * @return the value of t_disclosure_date.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_disclosure_date.update_time
     *
     * @param updateTime the value for t_disclosure_date.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}