package com.yskj.push.domain;

import java.util.Date;

public class Dividend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.div_proc
     *
     * @mbggenerated
     */
    private String divProc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.stk_div
     *
     * @mbggenerated
     */
    private String stkDiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.stk_bo_rate
     *
     * @mbggenerated
     */
    private String stkBoRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.stk_co_rate
     *
     * @mbggenerated
     */
    private String stkCoRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.cash_div
     *
     * @mbggenerated
     */
    private String cashDiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.cash_div_tax
     *
     * @mbggenerated
     */
    private String cashDivTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.record_date
     *
     * @mbggenerated
     */
    private String recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.ex_date
     *
     * @mbggenerated
     */
    private String exDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.pay_date
     *
     * @mbggenerated
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.div_listdate
     *
     * @mbggenerated
     */
    private String divListdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.imp_ann_date
     *
     * @mbggenerated
     */
    private String impAnnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.base_date
     *
     * @mbggenerated
     */
    private String baseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.base_share
     *
     * @mbggenerated
     */
    private String baseShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dividend.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.id
     *
     * @return the value of t_dividend.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.id
     *
     * @param id the value for t_dividend.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.ts_code
     *
     * @return the value of t_dividend.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.ts_code
     *
     * @param tsCode the value for t_dividend.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.end_date
     *
     * @return the value of t_dividend.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.end_date
     *
     * @param endDate the value for t_dividend.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.ann_date
     *
     * @return the value of t_dividend.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.ann_date
     *
     * @param annDate the value for t_dividend.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.div_proc
     *
     * @return the value of t_dividend.div_proc
     *
     * @mbggenerated
     */
    public String getDivProc() {
        return divProc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.div_proc
     *
     * @param divProc the value for t_dividend.div_proc
     *
     * @mbggenerated
     */
    public void setDivProc(String divProc) {
        this.divProc = divProc == null ? null : divProc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.stk_div
     *
     * @return the value of t_dividend.stk_div
     *
     * @mbggenerated
     */
    public String getStkDiv() {
        return stkDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.stk_div
     *
     * @param stkDiv the value for t_dividend.stk_div
     *
     * @mbggenerated
     */
    public void setStkDiv(String stkDiv) {
        this.stkDiv = stkDiv == null ? null : stkDiv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.stk_bo_rate
     *
     * @return the value of t_dividend.stk_bo_rate
     *
     * @mbggenerated
     */
    public String getStkBoRate() {
        return stkBoRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.stk_bo_rate
     *
     * @param stkBoRate the value for t_dividend.stk_bo_rate
     *
     * @mbggenerated
     */
    public void setStkBoRate(String stkBoRate) {
        this.stkBoRate = stkBoRate == null ? null : stkBoRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.stk_co_rate
     *
     * @return the value of t_dividend.stk_co_rate
     *
     * @mbggenerated
     */
    public String getStkCoRate() {
        return stkCoRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.stk_co_rate
     *
     * @param stkCoRate the value for t_dividend.stk_co_rate
     *
     * @mbggenerated
     */
    public void setStkCoRate(String stkCoRate) {
        this.stkCoRate = stkCoRate == null ? null : stkCoRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.cash_div
     *
     * @return the value of t_dividend.cash_div
     *
     * @mbggenerated
     */
    public String getCashDiv() {
        return cashDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.cash_div
     *
     * @param cashDiv the value for t_dividend.cash_div
     *
     * @mbggenerated
     */
    public void setCashDiv(String cashDiv) {
        this.cashDiv = cashDiv == null ? null : cashDiv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.cash_div_tax
     *
     * @return the value of t_dividend.cash_div_tax
     *
     * @mbggenerated
     */
    public String getCashDivTax() {
        return cashDivTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.cash_div_tax
     *
     * @param cashDivTax the value for t_dividend.cash_div_tax
     *
     * @mbggenerated
     */
    public void setCashDivTax(String cashDivTax) {
        this.cashDivTax = cashDivTax == null ? null : cashDivTax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.record_date
     *
     * @return the value of t_dividend.record_date
     *
     * @mbggenerated
     */
    public String getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.record_date
     *
     * @param recordDate the value for t_dividend.record_date
     *
     * @mbggenerated
     */
    public void setRecordDate(String recordDate) {
        this.recordDate = recordDate == null ? null : recordDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.ex_date
     *
     * @return the value of t_dividend.ex_date
     *
     * @mbggenerated
     */
    public String getExDate() {
        return exDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.ex_date
     *
     * @param exDate the value for t_dividend.ex_date
     *
     * @mbggenerated
     */
    public void setExDate(String exDate) {
        this.exDate = exDate == null ? null : exDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.pay_date
     *
     * @return the value of t_dividend.pay_date
     *
     * @mbggenerated
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.pay_date
     *
     * @param payDate the value for t_dividend.pay_date
     *
     * @mbggenerated
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate == null ? null : payDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.div_listdate
     *
     * @return the value of t_dividend.div_listdate
     *
     * @mbggenerated
     */
    public String getDivListdate() {
        return divListdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.div_listdate
     *
     * @param divListdate the value for t_dividend.div_listdate
     *
     * @mbggenerated
     */
    public void setDivListdate(String divListdate) {
        this.divListdate = divListdate == null ? null : divListdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.imp_ann_date
     *
     * @return the value of t_dividend.imp_ann_date
     *
     * @mbggenerated
     */
    public String getImpAnnDate() {
        return impAnnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.imp_ann_date
     *
     * @param impAnnDate the value for t_dividend.imp_ann_date
     *
     * @mbggenerated
     */
    public void setImpAnnDate(String impAnnDate) {
        this.impAnnDate = impAnnDate == null ? null : impAnnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.base_date
     *
     * @return the value of t_dividend.base_date
     *
     * @mbggenerated
     */
    public String getBaseDate() {
        return baseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.base_date
     *
     * @param baseDate the value for t_dividend.base_date
     *
     * @mbggenerated
     */
    public void setBaseDate(String baseDate) {
        this.baseDate = baseDate == null ? null : baseDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.base_share
     *
     * @return the value of t_dividend.base_share
     *
     * @mbggenerated
     */
    public String getBaseShare() {
        return baseShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.base_share
     *
     * @param baseShare the value for t_dividend.base_share
     *
     * @mbggenerated
     */
    public void setBaseShare(String baseShare) {
        this.baseShare = baseShare == null ? null : baseShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.create_time
     *
     * @return the value of t_dividend.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.create_time
     *
     * @param createTime the value for t_dividend.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dividend.update_time
     *
     * @return the value of t_dividend.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dividend.update_time
     *
     * @param updateTime the value for t_dividend.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}