package com.yskj.push.domain;

import java.util.Date;

public class Express {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.revenue
     *
     * @mbggenerated
     */
    private String revenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.operate_profit
     *
     * @mbggenerated
     */
    private String operateProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.total_profit
     *
     * @mbggenerated
     */
    private String totalProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.n_income
     *
     * @mbggenerated
     */
    private String nIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.total_assets
     *
     * @mbggenerated
     */
    private String totalAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.total_hldr_eqy_exc_min_int
     *
     * @mbggenerated
     */
    private String totalHldrEqyExcMinInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.diluted_eps
     *
     * @mbggenerated
     */
    private String dilutedEps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.diluted_roe
     *
     * @mbggenerated
     */
    private String dilutedRoe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.yoy_net_profit
     *
     * @mbggenerated
     */
    private String yoyNetProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.bps
     *
     * @mbggenerated
     */
    private String bps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.yoy_sales
     *
     * @mbggenerated
     */
    private String yoySales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.yoy_op
     *
     * @mbggenerated
     */
    private String yoyOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.yoy_tp
     *
     * @mbggenerated
     */
    private String yoyTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.yoy_dedu_np
     *
     * @mbggenerated
     */
    private String yoyDeduNp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.yoy_eps
     *
     * @mbggenerated
     */
    private String yoyEps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.yoy_roe
     *
     * @mbggenerated
     */
    private String yoyRoe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.growth_assets
     *
     * @mbggenerated
     */
    private String growthAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.yoy_equity
     *
     * @mbggenerated
     */
    private String yoyEquity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.growth_bps
     *
     * @mbggenerated
     */
    private String growthBps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.or_last_year
     *
     * @mbggenerated
     */
    private String orLastYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.op_last_year
     *
     * @mbggenerated
     */
    private String opLastYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.tp_last_year
     *
     * @mbggenerated
     */
    private String tpLastYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.np_last_year
     *
     * @mbggenerated
     */
    private String npLastYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.eps_last_year
     *
     * @mbggenerated
     */
    private String epsLastYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.open_net_assets
     *
     * @mbggenerated
     */
    private String openNetAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.open_bps
     *
     * @mbggenerated
     */
    private String openBps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.perf_summary
     *
     * @mbggenerated
     */
    private String perfSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.is_audit
     *
     * @mbggenerated
     */
    private String isAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.id
     *
     * @return the value of t_express.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.id
     *
     * @param id the value for t_express.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.ts_code
     *
     * @return the value of t_express.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.ts_code
     *
     * @param tsCode the value for t_express.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.ann_date
     *
     * @return the value of t_express.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.ann_date
     *
     * @param annDate the value for t_express.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.end_date
     *
     * @return the value of t_express.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.end_date
     *
     * @param endDate the value for t_express.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.revenue
     *
     * @return the value of t_express.revenue
     *
     * @mbggenerated
     */
    public String getRevenue() {
        return revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.revenue
     *
     * @param revenue the value for t_express.revenue
     *
     * @mbggenerated
     */
    public void setRevenue(String revenue) {
        this.revenue = revenue == null ? null : revenue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.operate_profit
     *
     * @return the value of t_express.operate_profit
     *
     * @mbggenerated
     */
    public String getOperateProfit() {
        return operateProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.operate_profit
     *
     * @param operateProfit the value for t_express.operate_profit
     *
     * @mbggenerated
     */
    public void setOperateProfit(String operateProfit) {
        this.operateProfit = operateProfit == null ? null : operateProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.total_profit
     *
     * @return the value of t_express.total_profit
     *
     * @mbggenerated
     */
    public String getTotalProfit() {
        return totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.total_profit
     *
     * @param totalProfit the value for t_express.total_profit
     *
     * @mbggenerated
     */
    public void setTotalProfit(String totalProfit) {
        this.totalProfit = totalProfit == null ? null : totalProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.n_income
     *
     * @return the value of t_express.n_income
     *
     * @mbggenerated
     */
    public String getnIncome() {
        return nIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.n_income
     *
     * @param nIncome the value for t_express.n_income
     *
     * @mbggenerated
     */
    public void setnIncome(String nIncome) {
        this.nIncome = nIncome == null ? null : nIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.total_assets
     *
     * @return the value of t_express.total_assets
     *
     * @mbggenerated
     */
    public String getTotalAssets() {
        return totalAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.total_assets
     *
     * @param totalAssets the value for t_express.total_assets
     *
     * @mbggenerated
     */
    public void setTotalAssets(String totalAssets) {
        this.totalAssets = totalAssets == null ? null : totalAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.total_hldr_eqy_exc_min_int
     *
     * @return the value of t_express.total_hldr_eqy_exc_min_int
     *
     * @mbggenerated
     */
    public String getTotalHldrEqyExcMinInt() {
        return totalHldrEqyExcMinInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.total_hldr_eqy_exc_min_int
     *
     * @param totalHldrEqyExcMinInt the value for t_express.total_hldr_eqy_exc_min_int
     *
     * @mbggenerated
     */
    public void setTotalHldrEqyExcMinInt(String totalHldrEqyExcMinInt) {
        this.totalHldrEqyExcMinInt = totalHldrEqyExcMinInt == null ? null : totalHldrEqyExcMinInt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.diluted_eps
     *
     * @return the value of t_express.diluted_eps
     *
     * @mbggenerated
     */
    public String getDilutedEps() {
        return dilutedEps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.diluted_eps
     *
     * @param dilutedEps the value for t_express.diluted_eps
     *
     * @mbggenerated
     */
    public void setDilutedEps(String dilutedEps) {
        this.dilutedEps = dilutedEps == null ? null : dilutedEps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.diluted_roe
     *
     * @return the value of t_express.diluted_roe
     *
     * @mbggenerated
     */
    public String getDilutedRoe() {
        return dilutedRoe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.diluted_roe
     *
     * @param dilutedRoe the value for t_express.diluted_roe
     *
     * @mbggenerated
     */
    public void setDilutedRoe(String dilutedRoe) {
        this.dilutedRoe = dilutedRoe == null ? null : dilutedRoe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.yoy_net_profit
     *
     * @return the value of t_express.yoy_net_profit
     *
     * @mbggenerated
     */
    public String getYoyNetProfit() {
        return yoyNetProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.yoy_net_profit
     *
     * @param yoyNetProfit the value for t_express.yoy_net_profit
     *
     * @mbggenerated
     */
    public void setYoyNetProfit(String yoyNetProfit) {
        this.yoyNetProfit = yoyNetProfit == null ? null : yoyNetProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.bps
     *
     * @return the value of t_express.bps
     *
     * @mbggenerated
     */
    public String getBps() {
        return bps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.bps
     *
     * @param bps the value for t_express.bps
     *
     * @mbggenerated
     */
    public void setBps(String bps) {
        this.bps = bps == null ? null : bps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.yoy_sales
     *
     * @return the value of t_express.yoy_sales
     *
     * @mbggenerated
     */
    public String getYoySales() {
        return yoySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.yoy_sales
     *
     * @param yoySales the value for t_express.yoy_sales
     *
     * @mbggenerated
     */
    public void setYoySales(String yoySales) {
        this.yoySales = yoySales == null ? null : yoySales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.yoy_op
     *
     * @return the value of t_express.yoy_op
     *
     * @mbggenerated
     */
    public String getYoyOp() {
        return yoyOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.yoy_op
     *
     * @param yoyOp the value for t_express.yoy_op
     *
     * @mbggenerated
     */
    public void setYoyOp(String yoyOp) {
        this.yoyOp = yoyOp == null ? null : yoyOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.yoy_tp
     *
     * @return the value of t_express.yoy_tp
     *
     * @mbggenerated
     */
    public String getYoyTp() {
        return yoyTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.yoy_tp
     *
     * @param yoyTp the value for t_express.yoy_tp
     *
     * @mbggenerated
     */
    public void setYoyTp(String yoyTp) {
        this.yoyTp = yoyTp == null ? null : yoyTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.yoy_dedu_np
     *
     * @return the value of t_express.yoy_dedu_np
     *
     * @mbggenerated
     */
    public String getYoyDeduNp() {
        return yoyDeduNp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.yoy_dedu_np
     *
     * @param yoyDeduNp the value for t_express.yoy_dedu_np
     *
     * @mbggenerated
     */
    public void setYoyDeduNp(String yoyDeduNp) {
        this.yoyDeduNp = yoyDeduNp == null ? null : yoyDeduNp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.yoy_eps
     *
     * @return the value of t_express.yoy_eps
     *
     * @mbggenerated
     */
    public String getYoyEps() {
        return yoyEps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.yoy_eps
     *
     * @param yoyEps the value for t_express.yoy_eps
     *
     * @mbggenerated
     */
    public void setYoyEps(String yoyEps) {
        this.yoyEps = yoyEps == null ? null : yoyEps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.yoy_roe
     *
     * @return the value of t_express.yoy_roe
     *
     * @mbggenerated
     */
    public String getYoyRoe() {
        return yoyRoe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.yoy_roe
     *
     * @param yoyRoe the value for t_express.yoy_roe
     *
     * @mbggenerated
     */
    public void setYoyRoe(String yoyRoe) {
        this.yoyRoe = yoyRoe == null ? null : yoyRoe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.growth_assets
     *
     * @return the value of t_express.growth_assets
     *
     * @mbggenerated
     */
    public String getGrowthAssets() {
        return growthAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.growth_assets
     *
     * @param growthAssets the value for t_express.growth_assets
     *
     * @mbggenerated
     */
    public void setGrowthAssets(String growthAssets) {
        this.growthAssets = growthAssets == null ? null : growthAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.yoy_equity
     *
     * @return the value of t_express.yoy_equity
     *
     * @mbggenerated
     */
    public String getYoyEquity() {
        return yoyEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.yoy_equity
     *
     * @param yoyEquity the value for t_express.yoy_equity
     *
     * @mbggenerated
     */
    public void setYoyEquity(String yoyEquity) {
        this.yoyEquity = yoyEquity == null ? null : yoyEquity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.growth_bps
     *
     * @return the value of t_express.growth_bps
     *
     * @mbggenerated
     */
    public String getGrowthBps() {
        return growthBps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.growth_bps
     *
     * @param growthBps the value for t_express.growth_bps
     *
     * @mbggenerated
     */
    public void setGrowthBps(String growthBps) {
        this.growthBps = growthBps == null ? null : growthBps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.or_last_year
     *
     * @return the value of t_express.or_last_year
     *
     * @mbggenerated
     */
    public String getOrLastYear() {
        return orLastYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.or_last_year
     *
     * @param orLastYear the value for t_express.or_last_year
     *
     * @mbggenerated
     */
    public void setOrLastYear(String orLastYear) {
        this.orLastYear = orLastYear == null ? null : orLastYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.op_last_year
     *
     * @return the value of t_express.op_last_year
     *
     * @mbggenerated
     */
    public String getOpLastYear() {
        return opLastYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.op_last_year
     *
     * @param opLastYear the value for t_express.op_last_year
     *
     * @mbggenerated
     */
    public void setOpLastYear(String opLastYear) {
        this.opLastYear = opLastYear == null ? null : opLastYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.tp_last_year
     *
     * @return the value of t_express.tp_last_year
     *
     * @mbggenerated
     */
    public String getTpLastYear() {
        return tpLastYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.tp_last_year
     *
     * @param tpLastYear the value for t_express.tp_last_year
     *
     * @mbggenerated
     */
    public void setTpLastYear(String tpLastYear) {
        this.tpLastYear = tpLastYear == null ? null : tpLastYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.np_last_year
     *
     * @return the value of t_express.np_last_year
     *
     * @mbggenerated
     */
    public String getNpLastYear() {
        return npLastYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.np_last_year
     *
     * @param npLastYear the value for t_express.np_last_year
     *
     * @mbggenerated
     */
    public void setNpLastYear(String npLastYear) {
        this.npLastYear = npLastYear == null ? null : npLastYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.eps_last_year
     *
     * @return the value of t_express.eps_last_year
     *
     * @mbggenerated
     */
    public String getEpsLastYear() {
        return epsLastYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.eps_last_year
     *
     * @param epsLastYear the value for t_express.eps_last_year
     *
     * @mbggenerated
     */
    public void setEpsLastYear(String epsLastYear) {
        this.epsLastYear = epsLastYear == null ? null : epsLastYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.open_net_assets
     *
     * @return the value of t_express.open_net_assets
     *
     * @mbggenerated
     */
    public String getOpenNetAssets() {
        return openNetAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.open_net_assets
     *
     * @param openNetAssets the value for t_express.open_net_assets
     *
     * @mbggenerated
     */
    public void setOpenNetAssets(String openNetAssets) {
        this.openNetAssets = openNetAssets == null ? null : openNetAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.open_bps
     *
     * @return the value of t_express.open_bps
     *
     * @mbggenerated
     */
    public String getOpenBps() {
        return openBps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.open_bps
     *
     * @param openBps the value for t_express.open_bps
     *
     * @mbggenerated
     */
    public void setOpenBps(String openBps) {
        this.openBps = openBps == null ? null : openBps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.perf_summary
     *
     * @return the value of t_express.perf_summary
     *
     * @mbggenerated
     */
    public String getPerfSummary() {
        return perfSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.perf_summary
     *
     * @param perfSummary the value for t_express.perf_summary
     *
     * @mbggenerated
     */
    public void setPerfSummary(String perfSummary) {
        this.perfSummary = perfSummary == null ? null : perfSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.is_audit
     *
     * @return the value of t_express.is_audit
     *
     * @mbggenerated
     */
    public String getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.is_audit
     *
     * @param isAudit the value for t_express.is_audit
     *
     * @mbggenerated
     */
    public void setIsAudit(String isAudit) {
        this.isAudit = isAudit == null ? null : isAudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.remark
     *
     * @return the value of t_express.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.remark
     *
     * @param remark the value for t_express.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.create_time
     *
     * @return the value of t_express.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.create_time
     *
     * @param createTime the value for t_express.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express.update_time
     *
     * @return the value of t_express.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express.update_time
     *
     * @param updateTime the value for t_express.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}