package com.yskj.push.domain;

import java.util.Date;

public class FinaMainbz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.bz_item
     *
     * @mbggenerated
     */
    private String bzItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.bz_sales
     *
     * @mbggenerated
     */
    private String bzSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.bz_profit
     *
     * @mbggenerated
     */
    private String bzProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.bz_cost
     *
     * @mbggenerated
     */
    private String bzCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.curr_type
     *
     * @mbggenerated
     */
    private String currType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.update_flag
     *
     * @mbggenerated
     */
    private String updateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_mainbz.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.id
     *
     * @return the value of t_fina_mainbz.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.id
     *
     * @param id the value for t_fina_mainbz.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.ts_code
     *
     * @return the value of t_fina_mainbz.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.ts_code
     *
     * @param tsCode the value for t_fina_mainbz.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.end_date
     *
     * @return the value of t_fina_mainbz.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.end_date
     *
     * @param endDate the value for t_fina_mainbz.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.bz_item
     *
     * @return the value of t_fina_mainbz.bz_item
     *
     * @mbggenerated
     */
    public String getBzItem() {
        return bzItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.bz_item
     *
     * @param bzItem the value for t_fina_mainbz.bz_item
     *
     * @mbggenerated
     */
    public void setBzItem(String bzItem) {
        this.bzItem = bzItem == null ? null : bzItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.bz_sales
     *
     * @return the value of t_fina_mainbz.bz_sales
     *
     * @mbggenerated
     */
    public String getBzSales() {
        return bzSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.bz_sales
     *
     * @param bzSales the value for t_fina_mainbz.bz_sales
     *
     * @mbggenerated
     */
    public void setBzSales(String bzSales) {
        this.bzSales = bzSales == null ? null : bzSales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.bz_profit
     *
     * @return the value of t_fina_mainbz.bz_profit
     *
     * @mbggenerated
     */
    public String getBzProfit() {
        return bzProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.bz_profit
     *
     * @param bzProfit the value for t_fina_mainbz.bz_profit
     *
     * @mbggenerated
     */
    public void setBzProfit(String bzProfit) {
        this.bzProfit = bzProfit == null ? null : bzProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.bz_cost
     *
     * @return the value of t_fina_mainbz.bz_cost
     *
     * @mbggenerated
     */
    public String getBzCost() {
        return bzCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.bz_cost
     *
     * @param bzCost the value for t_fina_mainbz.bz_cost
     *
     * @mbggenerated
     */
    public void setBzCost(String bzCost) {
        this.bzCost = bzCost == null ? null : bzCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.curr_type
     *
     * @return the value of t_fina_mainbz.curr_type
     *
     * @mbggenerated
     */
    public String getCurrType() {
        return currType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.curr_type
     *
     * @param currType the value for t_fina_mainbz.curr_type
     *
     * @mbggenerated
     */
    public void setCurrType(String currType) {
        this.currType = currType == null ? null : currType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.update_flag
     *
     * @return the value of t_fina_mainbz.update_flag
     *
     * @mbggenerated
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.update_flag
     *
     * @param updateFlag the value for t_fina_mainbz.update_flag
     *
     * @mbggenerated
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag == null ? null : updateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.create_time
     *
     * @return the value of t_fina_mainbz.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.create_time
     *
     * @param createTime the value for t_fina_mainbz.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_mainbz.update_time
     *
     * @return the value of t_fina_mainbz.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_mainbz.update_time
     *
     * @param updateTime the value for t_fina_mainbz.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}