package com.yskj.push.domain;

import java.util.Date;

public class FinaAudit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.audit_result
     *
     * @mbggenerated
     */
    private String auditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.audit_fees
     *
     * @mbggenerated
     */
    private String auditFees;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.audit_agency
     *
     * @mbggenerated
     */
    private String auditAgency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.audit_sign
     *
     * @mbggenerated
     */
    private String auditSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fina_audit.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.id
     *
     * @return the value of t_fina_audit.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.id
     *
     * @param id the value for t_fina_audit.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.ts_code
     *
     * @return the value of t_fina_audit.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.ts_code
     *
     * @param tsCode the value for t_fina_audit.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.ann_date
     *
     * @return the value of t_fina_audit.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.ann_date
     *
     * @param annDate the value for t_fina_audit.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.end_date
     *
     * @return the value of t_fina_audit.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.end_date
     *
     * @param endDate the value for t_fina_audit.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.audit_result
     *
     * @return the value of t_fina_audit.audit_result
     *
     * @mbggenerated
     */
    public String getAuditResult() {
        return auditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.audit_result
     *
     * @param auditResult the value for t_fina_audit.audit_result
     *
     * @mbggenerated
     */
    public void setAuditResult(String auditResult) {
        this.auditResult = auditResult == null ? null : auditResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.audit_fees
     *
     * @return the value of t_fina_audit.audit_fees
     *
     * @mbggenerated
     */
    public String getAuditFees() {
        return auditFees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.audit_fees
     *
     * @param auditFees the value for t_fina_audit.audit_fees
     *
     * @mbggenerated
     */
    public void setAuditFees(String auditFees) {
        this.auditFees = auditFees == null ? null : auditFees.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.audit_agency
     *
     * @return the value of t_fina_audit.audit_agency
     *
     * @mbggenerated
     */
    public String getAuditAgency() {
        return auditAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.audit_agency
     *
     * @param auditAgency the value for t_fina_audit.audit_agency
     *
     * @mbggenerated
     */
    public void setAuditAgency(String auditAgency) {
        this.auditAgency = auditAgency == null ? null : auditAgency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.audit_sign
     *
     * @return the value of t_fina_audit.audit_sign
     *
     * @mbggenerated
     */
    public String getAuditSign() {
        return auditSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.audit_sign
     *
     * @param auditSign the value for t_fina_audit.audit_sign
     *
     * @mbggenerated
     */
    public void setAuditSign(String auditSign) {
        this.auditSign = auditSign == null ? null : auditSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.create_time
     *
     * @return the value of t_fina_audit.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.create_time
     *
     * @param createTime the value for t_fina_audit.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fina_audit.update_time
     *
     * @return the value of t_fina_audit.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fina_audit.update_time
     *
     * @param updateTime the value for t_fina_audit.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}