package com.yskj.push.domain;

import java.util.Date;

public class Forecast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.p_change_min
     *
     * @mbggenerated
     */
    private String pChangeMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.p_change_max
     *
     * @mbggenerated
     */
    private String pChangeMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.net_profit_min
     *
     * @mbggenerated
     */
    private String netProfitMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.net_profit_max
     *
     * @mbggenerated
     */
    private String netProfitMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.last_parent_net
     *
     * @mbggenerated
     */
    private String lastParentNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.first_ann_date
     *
     * @mbggenerated
     */
    private String firstAnnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.change_reason
     *
     * @mbggenerated
     */
    private String changeReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_forecast.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.id
     *
     * @return the value of t_forecast.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.id
     *
     * @param id the value for t_forecast.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.ts_code
     *
     * @return the value of t_forecast.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.ts_code
     *
     * @param tsCode the value for t_forecast.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.ann_date
     *
     * @return the value of t_forecast.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.ann_date
     *
     * @param annDate the value for t_forecast.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.end_date
     *
     * @return the value of t_forecast.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.end_date
     *
     * @param endDate the value for t_forecast.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.type
     *
     * @return the value of t_forecast.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.type
     *
     * @param type the value for t_forecast.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.p_change_min
     *
     * @return the value of t_forecast.p_change_min
     *
     * @mbggenerated
     */
    public String getpChangeMin() {
        return pChangeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.p_change_min
     *
     * @param pChangeMin the value for t_forecast.p_change_min
     *
     * @mbggenerated
     */
    public void setpChangeMin(String pChangeMin) {
        this.pChangeMin = pChangeMin == null ? null : pChangeMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.p_change_max
     *
     * @return the value of t_forecast.p_change_max
     *
     * @mbggenerated
     */
    public String getpChangeMax() {
        return pChangeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.p_change_max
     *
     * @param pChangeMax the value for t_forecast.p_change_max
     *
     * @mbggenerated
     */
    public void setpChangeMax(String pChangeMax) {
        this.pChangeMax = pChangeMax == null ? null : pChangeMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.net_profit_min
     *
     * @return the value of t_forecast.net_profit_min
     *
     * @mbggenerated
     */
    public String getNetProfitMin() {
        return netProfitMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.net_profit_min
     *
     * @param netProfitMin the value for t_forecast.net_profit_min
     *
     * @mbggenerated
     */
    public void setNetProfitMin(String netProfitMin) {
        this.netProfitMin = netProfitMin == null ? null : netProfitMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.net_profit_max
     *
     * @return the value of t_forecast.net_profit_max
     *
     * @mbggenerated
     */
    public String getNetProfitMax() {
        return netProfitMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.net_profit_max
     *
     * @param netProfitMax the value for t_forecast.net_profit_max
     *
     * @mbggenerated
     */
    public void setNetProfitMax(String netProfitMax) {
        this.netProfitMax = netProfitMax == null ? null : netProfitMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.last_parent_net
     *
     * @return the value of t_forecast.last_parent_net
     *
     * @mbggenerated
     */
    public String getLastParentNet() {
        return lastParentNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.last_parent_net
     *
     * @param lastParentNet the value for t_forecast.last_parent_net
     *
     * @mbggenerated
     */
    public void setLastParentNet(String lastParentNet) {
        this.lastParentNet = lastParentNet == null ? null : lastParentNet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.first_ann_date
     *
     * @return the value of t_forecast.first_ann_date
     *
     * @mbggenerated
     */
    public String getFirstAnnDate() {
        return firstAnnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.first_ann_date
     *
     * @param firstAnnDate the value for t_forecast.first_ann_date
     *
     * @mbggenerated
     */
    public void setFirstAnnDate(String firstAnnDate) {
        this.firstAnnDate = firstAnnDate == null ? null : firstAnnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.summary
     *
     * @return the value of t_forecast.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.summary
     *
     * @param summary the value for t_forecast.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.change_reason
     *
     * @return the value of t_forecast.change_reason
     *
     * @mbggenerated
     */
    public String getChangeReason() {
        return changeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.change_reason
     *
     * @param changeReason the value for t_forecast.change_reason
     *
     * @mbggenerated
     */
    public void setChangeReason(String changeReason) {
        this.changeReason = changeReason == null ? null : changeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.create_time
     *
     * @return the value of t_forecast.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.create_time
     *
     * @param createTime the value for t_forecast.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_forecast.update_time
     *
     * @return the value of t_forecast.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_forecast.update_time
     *
     * @param updateTime the value for t_forecast.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}