package com.yskj.push.domain;

import java.util.Date;

public class Income {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.f_ann_date
     *
     * @mbggenerated
     */
    private String fAnnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.report_type
     *
     * @mbggenerated
     */
    private String reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.comp_type
     *
     * @mbggenerated
     */
    private String compType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.basic_eps
     *
     * @mbggenerated
     */
    private String basicEps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.diluted_eps
     *
     * @mbggenerated
     */
    private String dilutedEps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.total_revenue
     *
     * @mbggenerated
     */
    private String totalRevenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.revenue
     *
     * @mbggenerated
     */
    private String revenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.int_income
     *
     * @mbggenerated
     */
    private String intIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.prem_earned
     *
     * @mbggenerated
     */
    private String premEarned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.comm_income
     *
     * @mbggenerated
     */
    private String commIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.n_commis_income
     *
     * @mbggenerated
     */
    private String nCommisIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.n_oth_income
     *
     * @mbggenerated
     */
    private String nOthIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.n_oth_b_income
     *
     * @mbggenerated
     */
    private String nOthBIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.prem_income
     *
     * @mbggenerated
     */
    private String premIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.out_prem
     *
     * @mbggenerated
     */
    private String outPrem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.une_prem_reser
     *
     * @mbggenerated
     */
    private String unePremReser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.reins_income
     *
     * @mbggenerated
     */
    private String reinsIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.n_sec_tb_income
     *
     * @mbggenerated
     */
    private String nSecTbIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.n_sec_uw_income
     *
     * @mbggenerated
     */
    private String nSecUwIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.n_asset_mg_income
     *
     * @mbggenerated
     */
    private String nAssetMgIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.oth_b_income
     *
     * @mbggenerated
     */
    private String othBIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.fv_value_chg_gain
     *
     * @mbggenerated
     */
    private String fvValueChgGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.invest_income
     *
     * @mbggenerated
     */
    private String investIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.ass_invest_income
     *
     * @mbggenerated
     */
    private String assInvestIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.forex_gain
     *
     * @mbggenerated
     */
    private String forexGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.total_cogs
     *
     * @mbggenerated
     */
    private String totalCogs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.oper_cost
     *
     * @mbggenerated
     */
    private String operCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.int_exp
     *
     * @mbggenerated
     */
    private String intExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.comm_exp
     *
     * @mbggenerated
     */
    private String commExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.biz_tax_surchg
     *
     * @mbggenerated
     */
    private String bizTaxSurchg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.sell_exp
     *
     * @mbggenerated
     */
    private String sellExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.admin_exp
     *
     * @mbggenerated
     */
    private String adminExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.fin_exp
     *
     * @mbggenerated
     */
    private String finExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.assets_impair_loss
     *
     * @mbggenerated
     */
    private String assetsImpairLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.prem_refund
     *
     * @mbggenerated
     */
    private String premRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.compens_payout
     *
     * @mbggenerated
     */
    private String compensPayout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.reser_insur_liab
     *
     * @mbggenerated
     */
    private String reserInsurLiab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.div_payt
     *
     * @mbggenerated
     */
    private String divPayt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.reins_exp
     *
     * @mbggenerated
     */
    private String reinsExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.oper_exp
     *
     * @mbggenerated
     */
    private String operExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.compens_payout_refu
     *
     * @mbggenerated
     */
    private String compensPayoutRefu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.insur_reser_refu
     *
     * @mbggenerated
     */
    private String insurReserRefu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.reins_cost_refund
     *
     * @mbggenerated
     */
    private String reinsCostRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.other_bus_cost
     *
     * @mbggenerated
     */
    private String otherBusCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.operate_profit
     *
     * @mbggenerated
     */
    private String operateProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.non_oper_income
     *
     * @mbggenerated
     */
    private String nonOperIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.non_oper_exp
     *
     * @mbggenerated
     */
    private String nonOperExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.nca_disploss
     *
     * @mbggenerated
     */
    private String ncaDisploss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.total_profit
     *
     * @mbggenerated
     */
    private String totalProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.income_tax
     *
     * @mbggenerated
     */
    private String incomeTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.n_income
     *
     * @mbggenerated
     */
    private String nIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.n_income_attr_p
     *
     * @mbggenerated
     */
    private String nIncomeAttrP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.minority_gain
     *
     * @mbggenerated
     */
    private String minorityGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.oth_compr_income
     *
     * @mbggenerated
     */
    private String othComprIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.t_compr_income
     *
     * @mbggenerated
     */
    private String tComprIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.compr_inc_attr_p
     *
     * @mbggenerated
     */
    private String comprIncAttrP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.compr_inc_attr_m_s
     *
     * @mbggenerated
     */
    private String comprIncAttrMS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.ebit
     *
     * @mbggenerated
     */
    private String ebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.ebitda
     *
     * @mbggenerated
     */
    private String ebitda;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.insurance_exp
     *
     * @mbggenerated
     */
    private String insuranceExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.undist_profit
     *
     * @mbggenerated
     */
    private String undistProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.distable_profit
     *
     * @mbggenerated
     */
    private String distableProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.update_flag
     *
     * @mbggenerated
     */
    private String updateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.update_time
     *
     * @mbggenerated
     */
    private Date updateTime = new Date();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.id
     *
     * @return the value of t_income.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.id
     *
     * @param id the value for t_income.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.ts_code
     *
     * @return the value of t_income.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.ts_code
     *
     * @param tsCode the value for t_income.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.ann_date
     *
     * @return the value of t_income.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.ann_date
     *
     * @param annDate the value for t_income.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.f_ann_date
     *
     * @return the value of t_income.f_ann_date
     *
     * @mbggenerated
     */
    public String getfAnnDate() {
        return fAnnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.f_ann_date
     *
     * @param fAnnDate the value for t_income.f_ann_date
     *
     * @mbggenerated
     */
    public void setfAnnDate(String fAnnDate) {
        this.fAnnDate = fAnnDate == null ? null : fAnnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.end_date
     *
     * @return the value of t_income.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.end_date
     *
     * @param endDate the value for t_income.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.report_type
     *
     * @return the value of t_income.report_type
     *
     * @mbggenerated
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.report_type
     *
     * @param reportType the value for t_income.report_type
     *
     * @mbggenerated
     */
    public void setReportType(String reportType) {
        this.reportType = reportType == null ? null : reportType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.comp_type
     *
     * @return the value of t_income.comp_type
     *
     * @mbggenerated
     */
    public String getCompType() {
        return compType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.comp_type
     *
     * @param compType the value for t_income.comp_type
     *
     * @mbggenerated
     */
    public void setCompType(String compType) {
        this.compType = compType == null ? null : compType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.basic_eps
     *
     * @return the value of t_income.basic_eps
     *
     * @mbggenerated
     */
    public String getBasicEps() {
        return basicEps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.basic_eps
     *
     * @param basicEps the value for t_income.basic_eps
     *
     * @mbggenerated
     */
    public void setBasicEps(String basicEps) {
        this.basicEps = basicEps == null ? null : basicEps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.diluted_eps
     *
     * @return the value of t_income.diluted_eps
     *
     * @mbggenerated
     */
    public String getDilutedEps() {
        return dilutedEps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.diluted_eps
     *
     * @param dilutedEps the value for t_income.diluted_eps
     *
     * @mbggenerated
     */
    public void setDilutedEps(String dilutedEps) {
        this.dilutedEps = dilutedEps == null ? null : dilutedEps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.total_revenue
     *
     * @return the value of t_income.total_revenue
     *
     * @mbggenerated
     */
    public String getTotalRevenue() {
        return totalRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.total_revenue
     *
     * @param totalRevenue the value for t_income.total_revenue
     *
     * @mbggenerated
     */
    public void setTotalRevenue(String totalRevenue) {
        this.totalRevenue = totalRevenue == null ? null : totalRevenue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.revenue
     *
     * @return the value of t_income.revenue
     *
     * @mbggenerated
     */
    public String getRevenue() {
        return revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.revenue
     *
     * @param revenue the value for t_income.revenue
     *
     * @mbggenerated
     */
    public void setRevenue(String revenue) {
        this.revenue = revenue == null ? null : revenue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.int_income
     *
     * @return the value of t_income.int_income
     *
     * @mbggenerated
     */
    public String getIntIncome() {
        return intIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.int_income
     *
     * @param intIncome the value for t_income.int_income
     *
     * @mbggenerated
     */
    public void setIntIncome(String intIncome) {
        this.intIncome = intIncome == null ? null : intIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.prem_earned
     *
     * @return the value of t_income.prem_earned
     *
     * @mbggenerated
     */
    public String getPremEarned() {
        return premEarned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.prem_earned
     *
     * @param premEarned the value for t_income.prem_earned
     *
     * @mbggenerated
     */
    public void setPremEarned(String premEarned) {
        this.premEarned = premEarned == null ? null : premEarned.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.comm_income
     *
     * @return the value of t_income.comm_income
     *
     * @mbggenerated
     */
    public String getCommIncome() {
        return commIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.comm_income
     *
     * @param commIncome the value for t_income.comm_income
     *
     * @mbggenerated
     */
    public void setCommIncome(String commIncome) {
        this.commIncome = commIncome == null ? null : commIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.n_commis_income
     *
     * @return the value of t_income.n_commis_income
     *
     * @mbggenerated
     */
    public String getnCommisIncome() {
        return nCommisIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.n_commis_income
     *
     * @param nCommisIncome the value for t_income.n_commis_income
     *
     * @mbggenerated
     */
    public void setnCommisIncome(String nCommisIncome) {
        this.nCommisIncome = nCommisIncome == null ? null : nCommisIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.n_oth_income
     *
     * @return the value of t_income.n_oth_income
     *
     * @mbggenerated
     */
    public String getnOthIncome() {
        return nOthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.n_oth_income
     *
     * @param nOthIncome the value for t_income.n_oth_income
     *
     * @mbggenerated
     */
    public void setnOthIncome(String nOthIncome) {
        this.nOthIncome = nOthIncome == null ? null : nOthIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.n_oth_b_income
     *
     * @return the value of t_income.n_oth_b_income
     *
     * @mbggenerated
     */
    public String getnOthBIncome() {
        return nOthBIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.n_oth_b_income
     *
     * @param nOthBIncome the value for t_income.n_oth_b_income
     *
     * @mbggenerated
     */
    public void setnOthBIncome(String nOthBIncome) {
        this.nOthBIncome = nOthBIncome == null ? null : nOthBIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.prem_income
     *
     * @return the value of t_income.prem_income
     *
     * @mbggenerated
     */
    public String getPremIncome() {
        return premIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.prem_income
     *
     * @param premIncome the value for t_income.prem_income
     *
     * @mbggenerated
     */
    public void setPremIncome(String premIncome) {
        this.premIncome = premIncome == null ? null : premIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.out_prem
     *
     * @return the value of t_income.out_prem
     *
     * @mbggenerated
     */
    public String getOutPrem() {
        return outPrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.out_prem
     *
     * @param outPrem the value for t_income.out_prem
     *
     * @mbggenerated
     */
    public void setOutPrem(String outPrem) {
        this.outPrem = outPrem == null ? null : outPrem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.une_prem_reser
     *
     * @return the value of t_income.une_prem_reser
     *
     * @mbggenerated
     */
    public String getUnePremReser() {
        return unePremReser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.une_prem_reser
     *
     * @param unePremReser the value for t_income.une_prem_reser
     *
     * @mbggenerated
     */
    public void setUnePremReser(String unePremReser) {
        this.unePremReser = unePremReser == null ? null : unePremReser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.reins_income
     *
     * @return the value of t_income.reins_income
     *
     * @mbggenerated
     */
    public String getReinsIncome() {
        return reinsIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.reins_income
     *
     * @param reinsIncome the value for t_income.reins_income
     *
     * @mbggenerated
     */
    public void setReinsIncome(String reinsIncome) {
        this.reinsIncome = reinsIncome == null ? null : reinsIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.n_sec_tb_income
     *
     * @return the value of t_income.n_sec_tb_income
     *
     * @mbggenerated
     */
    public String getnSecTbIncome() {
        return nSecTbIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.n_sec_tb_income
     *
     * @param nSecTbIncome the value for t_income.n_sec_tb_income
     *
     * @mbggenerated
     */
    public void setnSecTbIncome(String nSecTbIncome) {
        this.nSecTbIncome = nSecTbIncome == null ? null : nSecTbIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.n_sec_uw_income
     *
     * @return the value of t_income.n_sec_uw_income
     *
     * @mbggenerated
     */
    public String getnSecUwIncome() {
        return nSecUwIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.n_sec_uw_income
     *
     * @param nSecUwIncome the value for t_income.n_sec_uw_income
     *
     * @mbggenerated
     */
    public void setnSecUwIncome(String nSecUwIncome) {
        this.nSecUwIncome = nSecUwIncome == null ? null : nSecUwIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.n_asset_mg_income
     *
     * @return the value of t_income.n_asset_mg_income
     *
     * @mbggenerated
     */
    public String getnAssetMgIncome() {
        return nAssetMgIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.n_asset_mg_income
     *
     * @param nAssetMgIncome the value for t_income.n_asset_mg_income
     *
     * @mbggenerated
     */
    public void setnAssetMgIncome(String nAssetMgIncome) {
        this.nAssetMgIncome = nAssetMgIncome == null ? null : nAssetMgIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.oth_b_income
     *
     * @return the value of t_income.oth_b_income
     *
     * @mbggenerated
     */
    public String getOthBIncome() {
        return othBIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.oth_b_income
     *
     * @param othBIncome the value for t_income.oth_b_income
     *
     * @mbggenerated
     */
    public void setOthBIncome(String othBIncome) {
        this.othBIncome = othBIncome == null ? null : othBIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.fv_value_chg_gain
     *
     * @return the value of t_income.fv_value_chg_gain
     *
     * @mbggenerated
     */
    public String getFvValueChgGain() {
        return fvValueChgGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.fv_value_chg_gain
     *
     * @param fvValueChgGain the value for t_income.fv_value_chg_gain
     *
     * @mbggenerated
     */
    public void setFvValueChgGain(String fvValueChgGain) {
        this.fvValueChgGain = fvValueChgGain == null ? null : fvValueChgGain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.invest_income
     *
     * @return the value of t_income.invest_income
     *
     * @mbggenerated
     */
    public String getInvestIncome() {
        return investIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.invest_income
     *
     * @param investIncome the value for t_income.invest_income
     *
     * @mbggenerated
     */
    public void setInvestIncome(String investIncome) {
        this.investIncome = investIncome == null ? null : investIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.ass_invest_income
     *
     * @return the value of t_income.ass_invest_income
     *
     * @mbggenerated
     */
    public String getAssInvestIncome() {
        return assInvestIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.ass_invest_income
     *
     * @param assInvestIncome the value for t_income.ass_invest_income
     *
     * @mbggenerated
     */
    public void setAssInvestIncome(String assInvestIncome) {
        this.assInvestIncome = assInvestIncome == null ? null : assInvestIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.forex_gain
     *
     * @return the value of t_income.forex_gain
     *
     * @mbggenerated
     */
    public String getForexGain() {
        return forexGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.forex_gain
     *
     * @param forexGain the value for t_income.forex_gain
     *
     * @mbggenerated
     */
    public void setForexGain(String forexGain) {
        this.forexGain = forexGain == null ? null : forexGain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.total_cogs
     *
     * @return the value of t_income.total_cogs
     *
     * @mbggenerated
     */
    public String getTotalCogs() {
        return totalCogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.total_cogs
     *
     * @param totalCogs the value for t_income.total_cogs
     *
     * @mbggenerated
     */
    public void setTotalCogs(String totalCogs) {
        this.totalCogs = totalCogs == null ? null : totalCogs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.oper_cost
     *
     * @return the value of t_income.oper_cost
     *
     * @mbggenerated
     */
    public String getOperCost() {
        return operCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.oper_cost
     *
     * @param operCost the value for t_income.oper_cost
     *
     * @mbggenerated
     */
    public void setOperCost(String operCost) {
        this.operCost = operCost == null ? null : operCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.int_exp
     *
     * @return the value of t_income.int_exp
     *
     * @mbggenerated
     */
    public String getIntExp() {
        return intExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.int_exp
     *
     * @param intExp the value for t_income.int_exp
     *
     * @mbggenerated
     */
    public void setIntExp(String intExp) {
        this.intExp = intExp == null ? null : intExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.comm_exp
     *
     * @return the value of t_income.comm_exp
     *
     * @mbggenerated
     */
    public String getCommExp() {
        return commExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.comm_exp
     *
     * @param commExp the value for t_income.comm_exp
     *
     * @mbggenerated
     */
    public void setCommExp(String commExp) {
        this.commExp = commExp == null ? null : commExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.biz_tax_surchg
     *
     * @return the value of t_income.biz_tax_surchg
     *
     * @mbggenerated
     */
    public String getBizTaxSurchg() {
        return bizTaxSurchg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.biz_tax_surchg
     *
     * @param bizTaxSurchg the value for t_income.biz_tax_surchg
     *
     * @mbggenerated
     */
    public void setBizTaxSurchg(String bizTaxSurchg) {
        this.bizTaxSurchg = bizTaxSurchg == null ? null : bizTaxSurchg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.sell_exp
     *
     * @return the value of t_income.sell_exp
     *
     * @mbggenerated
     */
    public String getSellExp() {
        return sellExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.sell_exp
     *
     * @param sellExp the value for t_income.sell_exp
     *
     * @mbggenerated
     */
    public void setSellExp(String sellExp) {
        this.sellExp = sellExp == null ? null : sellExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.admin_exp
     *
     * @return the value of t_income.admin_exp
     *
     * @mbggenerated
     */
    public String getAdminExp() {
        return adminExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.admin_exp
     *
     * @param adminExp the value for t_income.admin_exp
     *
     * @mbggenerated
     */
    public void setAdminExp(String adminExp) {
        this.adminExp = adminExp == null ? null : adminExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.fin_exp
     *
     * @return the value of t_income.fin_exp
     *
     * @mbggenerated
     */
    public String getFinExp() {
        return finExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.fin_exp
     *
     * @param finExp the value for t_income.fin_exp
     *
     * @mbggenerated
     */
    public void setFinExp(String finExp) {
        this.finExp = finExp == null ? null : finExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.assets_impair_loss
     *
     * @return the value of t_income.assets_impair_loss
     *
     * @mbggenerated
     */
    public String getAssetsImpairLoss() {
        return assetsImpairLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.assets_impair_loss
     *
     * @param assetsImpairLoss the value for t_income.assets_impair_loss
     *
     * @mbggenerated
     */
    public void setAssetsImpairLoss(String assetsImpairLoss) {
        this.assetsImpairLoss = assetsImpairLoss == null ? null : assetsImpairLoss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.prem_refund
     *
     * @return the value of t_income.prem_refund
     *
     * @mbggenerated
     */
    public String getPremRefund() {
        return premRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.prem_refund
     *
     * @param premRefund the value for t_income.prem_refund
     *
     * @mbggenerated
     */
    public void setPremRefund(String premRefund) {
        this.premRefund = premRefund == null ? null : premRefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.compens_payout
     *
     * @return the value of t_income.compens_payout
     *
     * @mbggenerated
     */
    public String getCompensPayout() {
        return compensPayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.compens_payout
     *
     * @param compensPayout the value for t_income.compens_payout
     *
     * @mbggenerated
     */
    public void setCompensPayout(String compensPayout) {
        this.compensPayout = compensPayout == null ? null : compensPayout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.reser_insur_liab
     *
     * @return the value of t_income.reser_insur_liab
     *
     * @mbggenerated
     */
    public String getReserInsurLiab() {
        return reserInsurLiab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.reser_insur_liab
     *
     * @param reserInsurLiab the value for t_income.reser_insur_liab
     *
     * @mbggenerated
     */
    public void setReserInsurLiab(String reserInsurLiab) {
        this.reserInsurLiab = reserInsurLiab == null ? null : reserInsurLiab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.div_payt
     *
     * @return the value of t_income.div_payt
     *
     * @mbggenerated
     */
    public String getDivPayt() {
        return divPayt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.div_payt
     *
     * @param divPayt the value for t_income.div_payt
     *
     * @mbggenerated
     */
    public void setDivPayt(String divPayt) {
        this.divPayt = divPayt == null ? null : divPayt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.reins_exp
     *
     * @return the value of t_income.reins_exp
     *
     * @mbggenerated
     */
    public String getReinsExp() {
        return reinsExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.reins_exp
     *
     * @param reinsExp the value for t_income.reins_exp
     *
     * @mbggenerated
     */
    public void setReinsExp(String reinsExp) {
        this.reinsExp = reinsExp == null ? null : reinsExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.oper_exp
     *
     * @return the value of t_income.oper_exp
     *
     * @mbggenerated
     */
    public String getOperExp() {
        return operExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.oper_exp
     *
     * @param operExp the value for t_income.oper_exp
     *
     * @mbggenerated
     */
    public void setOperExp(String operExp) {
        this.operExp = operExp == null ? null : operExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.compens_payout_refu
     *
     * @return the value of t_income.compens_payout_refu
     *
     * @mbggenerated
     */
    public String getCompensPayoutRefu() {
        return compensPayoutRefu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.compens_payout_refu
     *
     * @param compensPayoutRefu the value for t_income.compens_payout_refu
     *
     * @mbggenerated
     */
    public void setCompensPayoutRefu(String compensPayoutRefu) {
        this.compensPayoutRefu = compensPayoutRefu == null ? null : compensPayoutRefu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.insur_reser_refu
     *
     * @return the value of t_income.insur_reser_refu
     *
     * @mbggenerated
     */
    public String getInsurReserRefu() {
        return insurReserRefu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.insur_reser_refu
     *
     * @param insurReserRefu the value for t_income.insur_reser_refu
     *
     * @mbggenerated
     */
    public void setInsurReserRefu(String insurReserRefu) {
        this.insurReserRefu = insurReserRefu == null ? null : insurReserRefu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.reins_cost_refund
     *
     * @return the value of t_income.reins_cost_refund
     *
     * @mbggenerated
     */
    public String getReinsCostRefund() {
        return reinsCostRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.reins_cost_refund
     *
     * @param reinsCostRefund the value for t_income.reins_cost_refund
     *
     * @mbggenerated
     */
    public void setReinsCostRefund(String reinsCostRefund) {
        this.reinsCostRefund = reinsCostRefund == null ? null : reinsCostRefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.other_bus_cost
     *
     * @return the value of t_income.other_bus_cost
     *
     * @mbggenerated
     */
    public String getOtherBusCost() {
        return otherBusCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.other_bus_cost
     *
     * @param otherBusCost the value for t_income.other_bus_cost
     *
     * @mbggenerated
     */
    public void setOtherBusCost(String otherBusCost) {
        this.otherBusCost = otherBusCost == null ? null : otherBusCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.operate_profit
     *
     * @return the value of t_income.operate_profit
     *
     * @mbggenerated
     */
    public String getOperateProfit() {
        return operateProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.operate_profit
     *
     * @param operateProfit the value for t_income.operate_profit
     *
     * @mbggenerated
     */
    public void setOperateProfit(String operateProfit) {
        this.operateProfit = operateProfit == null ? null : operateProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.non_oper_income
     *
     * @return the value of t_income.non_oper_income
     *
     * @mbggenerated
     */
    public String getNonOperIncome() {
        return nonOperIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.non_oper_income
     *
     * @param nonOperIncome the value for t_income.non_oper_income
     *
     * @mbggenerated
     */
    public void setNonOperIncome(String nonOperIncome) {
        this.nonOperIncome = nonOperIncome == null ? null : nonOperIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.non_oper_exp
     *
     * @return the value of t_income.non_oper_exp
     *
     * @mbggenerated
     */
    public String getNonOperExp() {
        return nonOperExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.non_oper_exp
     *
     * @param nonOperExp the value for t_income.non_oper_exp
     *
     * @mbggenerated
     */
    public void setNonOperExp(String nonOperExp) {
        this.nonOperExp = nonOperExp == null ? null : nonOperExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.nca_disploss
     *
     * @return the value of t_income.nca_disploss
     *
     * @mbggenerated
     */
    public String getNcaDisploss() {
        return ncaDisploss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.nca_disploss
     *
     * @param ncaDisploss the value for t_income.nca_disploss
     *
     * @mbggenerated
     */
    public void setNcaDisploss(String ncaDisploss) {
        this.ncaDisploss = ncaDisploss == null ? null : ncaDisploss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.total_profit
     *
     * @return the value of t_income.total_profit
     *
     * @mbggenerated
     */
    public String getTotalProfit() {
        return totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.total_profit
     *
     * @param totalProfit the value for t_income.total_profit
     *
     * @mbggenerated
     */
    public void setTotalProfit(String totalProfit) {
        this.totalProfit = totalProfit == null ? null : totalProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.income_tax
     *
     * @return the value of t_income.income_tax
     *
     * @mbggenerated
     */
    public String getIncomeTax() {
        return incomeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.income_tax
     *
     * @param incomeTax the value for t_income.income_tax
     *
     * @mbggenerated
     */
    public void setIncomeTax(String incomeTax) {
        this.incomeTax = incomeTax == null ? null : incomeTax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.n_income
     *
     * @return the value of t_income.n_income
     *
     * @mbggenerated
     */
    public String getnIncome() {
        return nIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.n_income
     *
     * @param nIncome the value for t_income.n_income
     *
     * @mbggenerated
     */
    public void setnIncome(String nIncome) {
        this.nIncome = nIncome == null ? null : nIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.n_income_attr_p
     *
     * @return the value of t_income.n_income_attr_p
     *
     * @mbggenerated
     */
    public String getnIncomeAttrP() {
        return nIncomeAttrP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.n_income_attr_p
     *
     * @param nIncomeAttrP the value for t_income.n_income_attr_p
     *
     * @mbggenerated
     */
    public void setnIncomeAttrP(String nIncomeAttrP) {
        this.nIncomeAttrP = nIncomeAttrP == null ? null : nIncomeAttrP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.minority_gain
     *
     * @return the value of t_income.minority_gain
     *
     * @mbggenerated
     */
    public String getMinorityGain() {
        return minorityGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.minority_gain
     *
     * @param minorityGain the value for t_income.minority_gain
     *
     * @mbggenerated
     */
    public void setMinorityGain(String minorityGain) {
        this.minorityGain = minorityGain == null ? null : minorityGain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.oth_compr_income
     *
     * @return the value of t_income.oth_compr_income
     *
     * @mbggenerated
     */
    public String getOthComprIncome() {
        return othComprIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.oth_compr_income
     *
     * @param othComprIncome the value for t_income.oth_compr_income
     *
     * @mbggenerated
     */
    public void setOthComprIncome(String othComprIncome) {
        this.othComprIncome = othComprIncome == null ? null : othComprIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.t_compr_income
     *
     * @return the value of t_income.t_compr_income
     *
     * @mbggenerated
     */
    public String gettComprIncome() {
        return tComprIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.t_compr_income
     *
     * @param tComprIncome the value for t_income.t_compr_income
     *
     * @mbggenerated
     */
    public void settComprIncome(String tComprIncome) {
        this.tComprIncome = tComprIncome == null ? null : tComprIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.compr_inc_attr_p
     *
     * @return the value of t_income.compr_inc_attr_p
     *
     * @mbggenerated
     */
    public String getComprIncAttrP() {
        return comprIncAttrP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.compr_inc_attr_p
     *
     * @param comprIncAttrP the value for t_income.compr_inc_attr_p
     *
     * @mbggenerated
     */
    public void setComprIncAttrP(String comprIncAttrP) {
        this.comprIncAttrP = comprIncAttrP == null ? null : comprIncAttrP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.compr_inc_attr_m_s
     *
     * @return the value of t_income.compr_inc_attr_m_s
     *
     * @mbggenerated
     */
    public String getComprIncAttrMS() {
        return comprIncAttrMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.compr_inc_attr_m_s
     *
     * @param comprIncAttrMS the value for t_income.compr_inc_attr_m_s
     *
     * @mbggenerated
     */
    public void setComprIncAttrMS(String comprIncAttrMS) {
        this.comprIncAttrMS = comprIncAttrMS == null ? null : comprIncAttrMS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.ebit
     *
     * @return the value of t_income.ebit
     *
     * @mbggenerated
     */
    public String getEbit() {
        return ebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.ebit
     *
     * @param ebit the value for t_income.ebit
     *
     * @mbggenerated
     */
    public void setEbit(String ebit) {
        this.ebit = ebit == null ? null : ebit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.ebitda
     *
     * @return the value of t_income.ebitda
     *
     * @mbggenerated
     */
    public String getEbitda() {
        return ebitda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.ebitda
     *
     * @param ebitda the value for t_income.ebitda
     *
     * @mbggenerated
     */
    public void setEbitda(String ebitda) {
        this.ebitda = ebitda == null ? null : ebitda.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.insurance_exp
     *
     * @return the value of t_income.insurance_exp
     *
     * @mbggenerated
     */
    public String getInsuranceExp() {
        return insuranceExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.insurance_exp
     *
     * @param insuranceExp the value for t_income.insurance_exp
     *
     * @mbggenerated
     */
    public void setInsuranceExp(String insuranceExp) {
        this.insuranceExp = insuranceExp == null ? null : insuranceExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.undist_profit
     *
     * @return the value of t_income.undist_profit
     *
     * @mbggenerated
     */
    public String getUndistProfit() {
        return undistProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.undist_profit
     *
     * @param undistProfit the value for t_income.undist_profit
     *
     * @mbggenerated
     */
    public void setUndistProfit(String undistProfit) {
        this.undistProfit = undistProfit == null ? null : undistProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.distable_profit
     *
     * @return the value of t_income.distable_profit
     *
     * @mbggenerated
     */
    public String getDistableProfit() {
        return distableProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.distable_profit
     *
     * @param distableProfit the value for t_income.distable_profit
     *
     * @mbggenerated
     */
    public void setDistableProfit(String distableProfit) {
        this.distableProfit = distableProfit == null ? null : distableProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.update_flag
     *
     * @return the value of t_income.update_flag
     *
     * @mbggenerated
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.update_flag
     *
     * @param updateFlag the value for t_income.update_flag
     *
     * @mbggenerated
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag == null ? null : updateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.create_time
     *
     * @return the value of t_income.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.create_time
     *
     * @param createTime the value for t_income.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.update_time
     *
     * @return the value of t_income.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.update_time
     *
     * @param updateTime the value for t_income.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}