package com.yskj.push.domain;

import com.yskj.push.framework.util.DateUtil;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.news_datetime
     *
     * @mbggenerated
     */
    private Date newsDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.channels
     *
     * @mbggenerated
     */
    private String channels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.content
     *
     * @mbggenerated
     */
    private String content;

    private String datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.id
     *
     * @return the value of t_news.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.id
     *
     * @param id the value for t_news.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.news_datetime
     *
     * @return the value of t_news.news_datetime
     *
     * @mbggenerated
     */
    public Date getNewsDatetime() {
        return newsDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.news_datetime
     *
     * @param newsDatetime the value for t_news.news_datetime
     *
     * @mbggenerated
     */
    public void setNewsDatetime(Date newsDatetime) {
        this.newsDatetime = newsDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.title
     *
     * @return the value of t_news.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.title
     *
     * @param title the value for t_news.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.channels
     *
     * @return the value of t_news.channels
     *
     * @mbggenerated
     */
    public String getChannels() {
        return channels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.channels
     *
     * @param channels the value for t_news.channels
     *
     * @mbggenerated
     */
    public void setChannels(String channels) {
        this.channels = channels == null ? null : channels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.create_time
     *
     * @return the value of t_news.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.create_time
     *
     * @param createTime the value for t_news.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.update_time
     *
     * @return the value of t_news.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.update_time
     *
     * @param updateTime the value for t_news.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.content
     *
     * @return the value of t_news.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.content
     *
     * @param content the value for t_news.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getDatetime() {
        return DateUtil.getFormatDate(getNewsDatetime(), "yyyy-MM-dd HH:mm:ss");
    }

    public void setDatetime(String datetime) {
        this.datetime = datetime;
        this.newsDatetime = DateUtil.parseDate(datetime, "yyyy-MM-dd HH:mm:ss");
    }
}