package com.yskj.push.domain;

import java.util.Date;

public class Top10FloatHolders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_top10_float_holders.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_top10_float_holders.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_top10_float_holders.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_top10_float_holders.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_top10_float_holders.holder_name
     *
     * @mbggenerated
     */
    private String holderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_top10_float_holders.hold_amount
     *
     * @mbggenerated
     */
    private String holdAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_top10_float_holders.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_top10_float_holders.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_top10_float_holders.id
     *
     * @return the value of t_top10_float_holders.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_top10_float_holders.id
     *
     * @param id the value for t_top10_float_holders.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_top10_float_holders.ts_code
     *
     * @return the value of t_top10_float_holders.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_top10_float_holders.ts_code
     *
     * @param tsCode the value for t_top10_float_holders.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_top10_float_holders.ann_date
     *
     * @return the value of t_top10_float_holders.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_top10_float_holders.ann_date
     *
     * @param annDate the value for t_top10_float_holders.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_top10_float_holders.end_date
     *
     * @return the value of t_top10_float_holders.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_top10_float_holders.end_date
     *
     * @param endDate the value for t_top10_float_holders.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_top10_float_holders.holder_name
     *
     * @return the value of t_top10_float_holders.holder_name
     *
     * @mbggenerated
     */
    public String getHolderName() {
        return holderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_top10_float_holders.holder_name
     *
     * @param holderName the value for t_top10_float_holders.holder_name
     *
     * @mbggenerated
     */
    public void setHolderName(String holderName) {
        this.holderName = holderName == null ? null : holderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_top10_float_holders.hold_amount
     *
     * @return the value of t_top10_float_holders.hold_amount
     *
     * @mbggenerated
     */
    public String getHoldAmount() {
        return holdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_top10_float_holders.hold_amount
     *
     * @param holdAmount the value for t_top10_float_holders.hold_amount
     *
     * @mbggenerated
     */
    public void setHoldAmount(String holdAmount) {
        this.holdAmount = holdAmount == null ? null : holdAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_top10_float_holders.create_time
     *
     * @return the value of t_top10_float_holders.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_top10_float_holders.create_time
     *
     * @param createTime the value for t_top10_float_holders.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_top10_float_holders.update_time
     *
     * @return the value of t_top10_float_holders.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_top10_float_holders.update_time
     *
     * @param updateTime the value for t_top10_float_holders.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}