package com.yskj.push.domain;

import java.util.Date;

public class CorpImport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.reffer
     *
     * @mbggenerated
     */
    private String reffer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.active_id
     *
     * @mbggenerated
     */
    private String activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.adviser_code
     *
     * @mbggenerated
     */
    private String adviserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.fail_reason
     *
     * @mbggenerated
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp_import.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.id
     *
     * @return the value of t_corp_import.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.id
     *
     * @param id the value for t_corp_import.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.nick_name
     *
     * @return the value of t_corp_import.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.nick_name
     *
     * @param nickName the value for t_corp_import.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.phone
     *
     * @return the value of t_corp_import.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.phone
     *
     * @param phone the value for t_corp_import.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.reffer
     *
     * @return the value of t_corp_import.reffer
     *
     * @mbggenerated
     */
    public String getReffer() {
        return reffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.reffer
     *
     * @param reffer the value for t_corp_import.reffer
     *
     * @mbggenerated
     */
    public void setReffer(String reffer) {
        this.reffer = reffer == null ? null : reffer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.active_id
     *
     * @return the value of t_corp_import.active_id
     *
     * @mbggenerated
     */
    public String getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.active_id
     *
     * @param activeId the value for t_corp_import.active_id
     *
     * @mbggenerated
     */
    public void setActiveId(String activeId) {
        this.activeId = activeId == null ? null : activeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.adviser_code
     *
     * @return the value of t_corp_import.adviser_code
     *
     * @mbggenerated
     */
    public String getAdviserCode() {
        return adviserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.adviser_code
     *
     * @param adviserCode the value for t_corp_import.adviser_code
     *
     * @mbggenerated
     */
    public void setAdviserCode(String adviserCode) {
        this.adviserCode = adviserCode == null ? null : adviserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.status
     *
     * @return the value of t_corp_import.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.status
     *
     * @param status the value for t_corp_import.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.fail_reason
     *
     * @return the value of t_corp_import.fail_reason
     *
     * @mbggenerated
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.fail_reason
     *
     * @param failReason the value for t_corp_import.fail_reason
     *
     * @mbggenerated
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.createTime
     *
     * @return the value of t_corp_import.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.createTime
     *
     * @param createtime the value for t_corp_import.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp_import.updateTime
     *
     * @return the value of t_corp_import.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp_import.updateTime
     *
     * @param updatetime the value for t_corp_import.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}